### ISSUE TITLE
Unable to make acs commons module active under console/bundles

### ISSUE THREAD

**Issue by perfeccionista** [Adobe-Consulting-Services/acs-aem-commons#1015]
I am using AEM 6.2 and ACS Commons 3.9 on a windows environment with Java8. 

```
com.adobe.acs.commons.workflow.synthetic,version=[2.0,3) from com.adobe.acs.acs-aem-commons-bundle (444)
com.adobe.cq.dialogconversion,version=[1.0,2) -- Cannot be resolved but is not required
com.adobe.granite.asset.api,version=[1.4,2) from com.adobe.granite.asset.api (144)
com.adobe.granite.jmx.annotation,version=[1.0,2) from com.adobe.granite.jmx (100)
com.adobe.granite.license,version=[1.1,2) from com.adobe.granite.license (65)
com.adobe.granite.security.user,version=[1.6,2) -- Cannot be resolved
com.adobe.granite.taskmanagement,version=[1.0,2) from com.adobe.granite.taskmanagement.api (187)
com.adobe.granite.ui.clientlibs,version=[1.0,2) from com.adobe.granite.ui.clientlibs (191)
com.adobe.granite.ui.components.ds,version=[1.1,2) -- Cannot be resolved
com.adobe.granite.workflow,version=[1.0,2) from com.adobe.granite.workflow.api (194)
com.adobe.granite.workflow.collection.util,version=[1.0,2) from com.adobe.granite.workflow.api (194)
com.adobe.granite.workflow.exec,version=[1.1,2) -- Cannot be resolved
com.adobe.granite.workflow.exec.filter,version=[1.0,2) from com.adobe.granite.workflow.api (194)
com.adobe.granite.workflow.metadata,version=[1.0,2) from com.adobe.granite.workflow.api (194)
com.adobe.granite.workflow.model,version=[1.0,2) from com.adobe.granite.workflow.api (194)
com.adobe.granite.xss,version=[1.1,2) from com.day.cq.cq-xssprotection (197)
com.day.cq.commons,version=[6.0,7) -- Cannot be resolved
com.day.cq.commons.feed,version=[5.7,6) from com.day.cq.cq-commons (292)
com.day.cq.commons.inherit,version=[5.7,6) from com.day.cq.cq-commons (292)
com.day.cq.commons.jcr,version=[6.0,7) -- Cannot be resolved
com.day.cq.commons.mail,version=[5.7,6) from com.day.cq.cq-commons (292)
com.day.cq.dam.api,version=[1.16,2) -- Cannot be resolved
com.day.cq.dam.commons.util,version=[1.24,2) -- Cannot be resolved
com.day.cq.dam.handler.ffmpeg,version=[5.9,6) -- Cannot be resolved
com.day.cq.dam.video,version=[5.9,6) -- Cannot be resolved
com.day.cq.jcrclustersupport,version=[2.0,3) from com.day.cq.cq-jcrclustersupport (114)
com.day.cq.mailer,version=[5.9,7) from com.day.cq.cq-mailer (296)
com.day.cq.polling.importer,version=[5.8,6) from com.day.cq.cq-polling-importer (301)
com.day.cq.replication,version=[6.1,7) -- Cannot be resolved
com.day.cq.search,version=[1.2,2) -- Cannot be resolved
com.day.cq.search.eval,version=[1.2,2) -- Cannot be resolved
com.day.cq.search.result,version=[1.2,2) from com.day.cq.cq-search (307)
com.day.cq.search.writer,version=[1.0,2) from com.day.cq.cq-search (307)
com.day.cq.wcm.api,version=[1.17,2) -- Cannot be resolved
com.day.cq.wcm.api.components,version=[5.8,6) -- Cannot be resolved
com.day.cq.wcm.api.designer,version=[5.8,6) -- Cannot be resolved
com.day.cq.wcm.api.reference,version=[1.1,2) from com.day.cq.wcm.cq-wcm-api (419)
com.day.cq.wcm.commons,version=[5.8,6) from com.day.cq.wcm.cq-wcm-commons (420)
com.day.cq.wcm.core.contentfinder,version=[5.10,6) -- Cannot be resolved
com.day.cq.wcm.foundation,version=[5.20,6) -- Cannot be resolved
com.day.cq.wcm.workflow.process,version=[6.0,8) -- Cannot be resolved
com.day.cq.workflow,version=[1.0,2) -- Cannot be resolved
com.day.cq.workflow.collection,version=[1.0,2) -- Cannot be resolved
com.day.cq.workflow.collection.util,version=[1.0,2) -- Cannot be resolved
com.day.cq.workflow.exec,version=[1.0,2) -- Cannot be resolved
com.day.cq.workflow.exec.filter,version=[1.0,2) -- Cannot be resolved
com.day.cq.workflow.metadata,version=[1.0,2) -- Cannot be resolved
com.day.cq.workflow.model,version=[1.0,2) -- Cannot be resolved
com.day.image,version=[1.0,2) from day-commons-gfx (205)
```
 

On activating the bundle, following error shown in error.log.

```
23.05.2017 21:20:55.266 *INFO* [OsgiInstallerImpl] org.apache.sling.installer.core.impl.tasks.BundleStartTask Could not start bundle com.adobe.acs.acs-aem-commons-bundle [444]. Reason: {}. Will retry.
org.osgi.framework.BundleException: Unresolved constraint in bundle com.adobe.acs.acs-aem-commons-bundle [444]: Unable to resolve 444.0: missing requirement [444.0] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.wcm.workflow.process)(version>=6.0.0)(!(version>=8.0.0)))
    at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4095)
    at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
    at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:977)
    at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:964)
    at org.apache.sling.installer.core.impl.tasks.BundleStartTask.execute(BundleStartTask.java:93)
    at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:847)
    at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:689)
    at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:265)
    at java.lang.Thread.run(Unknown Source)
23.05.2017 21:20:55.266 *INFO* [OsgiInstallerImpl] org.apache.sling.installer.core.impl.tasks.BundleStartTask Could not start bundle com.adobe.acs.acs-aem-commons-bundle-twitter [445]. Reason: {}. Will retry.
org.osgi.framework.BundleException: Unresolved constraint in bundle com.adobe.acs.acs-aem-commons-bundle-twitter [445]: Unable to resolve 445.0: missing requirement [445.0] osgi.wiring.package; (&(osgi.wiring.package=twitter4j)(version>=3.0.5)(!(version>=4.0.0)))
    at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4095)
    at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
    at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:977)
    at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:964)
    at org.apache.sling.installer.core.impl.tasks.BundleStartTask.execute(BundleStartTask.java:93)
    at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:847)
    at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:689)
    at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:265)
    at java.lang.Thread.run(Unknown Source)
23.05.2017 21:21:52.680 *INFO* [oak-repository-executor-1] com.adobe.granite.repository Service [3374, [org.apache.jackrabbit.oak.api.jmx.SessionMBean]] ServiceEvent REGISTERED
23.05.2017 21:22:25.123 *INFO* [pool-7-thread-4] com.day.cq.statistics.impl.StatisticsServiceImpl Running clean up reports...
23.05.2017 21:22:25.123 *WARN* [pool-7-thread-4] org.apache.jackrabbit.oak.jcr.session.RefreshStrategy This session has been idle for 5 minutes and might be out of date. Consider using a fresh session or explicitly refresh the session.
java.lang.Exception: The session was created here:
    at org.apache.jackrabbit.oak.jcr.session.RefreshStrategy$LogOnce.<init>(RefreshStrategy.java:169)
```

Help much appreciated.

**Comment by erved** [comment]
can I know the Java and Maven version ? you using

**Comment by erved** [comment]
Try to add these dependency in content/POM.xml
_____________________________________________________________
<dependency>
    <groupId>com.adobe.acs</groupId>
    <artifactId>acs-aem-commons-content</artifactId>
    <version>3.9.0</version>
    <type>content-package</type>
</dependency>

**Comment by perfeccionista** [comment]
I have using java 1.8 version.

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:4
7-06:00)
Maven home: C:\Adobe\apache-maven\bin\..
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: C:\Installations\Java\jdk1.8.0_121\jre
Default locale: en_US, platform encoding: Cp1252

My main POM file has this entry.

<dependency>
                <groupId>com.adobe.acs</groupId>
                <artifactId>acs-aem-commons-bundle</artifactId>
                <version>3.4.0</version>
                <scope>provided</scope>
            </dependency>
						
			<dependency>
                <groupId>com.adobe.acs</groupId>
                <artifactId>acs-aem-commons-content</artifactId>
                <version>3.4.0</version>
				<type>content-package</type>
                <scope>provided</scope>
            </dependency>

**Comment by davidjgonzalez** [comment]
@perfeccionista in the first post you say you're using 3.9.0.. but here it appears you're using 3.4.0...
have you manually deployed 3.9.0 to your AEM instance? You should make sure that you are in sync across your ACS Commons versions (the dep versions in your maven pom and what is deployed to AEM) .. if they are different you can certainly get dependency resolution issues.

**Comment by anujrattan** [comment]
In our project we have used version 3.8.4 for both acs-commons-bundle and acs-commons-content. it works fine for us.

**Comment by justinedelson** [comment]
no feedback in several months. closing
