### ISSUE TITLE
Improve logging in case of 404 in ErrorPageHandler

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#1086]
Sometimes we have this error message in our log (AEM 6.1)

```
22.08.2017 11:50:49.877 *ERROR* [10.225.147.9 [1503395449831] GET /libs/granite/core/content/login/clientlib/resources/bg/db/bg.css HTTP/1.1] com.adobe.acs.commons.util.ResourceDataUtil Error creating the String representation for: /content/ab/cd/error/404.html -- {}
org.apache.sling.api.resource.ResourceNotFoundException: No resource found
                at org.apache.sling.servlets.get.impl.DefaultGetServlet.doGet(DefaultGetServlet.java:219)
                at org.apache.sling.api.servlets.SlingSafeMethodsServlet.mayService(SlingSafeMethodsServlet.java:269)
                at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:345)
                at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:376)
```

To improve the log message "Error creating the String representation for: /content/ab/cd/error/404.html -- {}", I would suggest to change line 59 in ResourceDataUtil.java

```
log.error("Error creating the String representation for: {} -- {}", path, ex);
```

to 
```
log.error("Error creating the String representation for: {}", path, ex);
```

**Comment by justinedelson** [comment]
Actually, I think the fix is to do the string concatenation and log the exception.
