### ISSUE TITLE
Property merge post processor with relative attributes

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#1193]
I am trying to use this feature in conjunction with the asset schema editor, but when I specify a relative property for the merge value, I get a stacktrace:

```29.11.2017 17:33:33.041 *ERROR* [0:0:0:0:0:0:0:1 [1511998413034] POST /content/dam.html HTTP/1.1] org.apache.sling.servlets.post.impl.operations.ModifyOperation Exception during response processing.
java.lang.IllegalArgumentException: Invalid key: jcr:content/metadata/dam:tags-merged
        at org.apache.sling.jcr.resource.internal.JcrModifiableValueMap.put(JcrModifiableValueMap.java:437)
        at org.apache.sling.jcr.resource.internal.JcrModifiableValueMap.put(JcrModifiableValueMap.java:47)
        at com.adobe.acs.commons.wcm.impl.PropertyMergePostProcessor.merge(PropertyMergePostProcessor.java:173)
        at com.adobe.acs.commons.wcm.impl.PropertyMergePostProcessor.process(PropertyMergePostProcessor.java:51)
        at org.apache.sling.servlets.post.AbstractPostOperation.run(AbstractPostOperation.java:102)
        at org.apache.sling.servlets.post.impl.SlingPostServlet.doPost(SlingPostServlet.java:205)
        at org.apache.sling.api.servlets.SlingAllMethodsServlet.mayService(SlingAllMethodsServlet.java:149)
        at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:346)
        at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:378)
        at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:552)
        at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
...```

**Comment by davidjgonzalez** [comment]
@badvision you planning on picking this one up? dont want to step on your toes.

**Comment by badvision** [comment]
Yes, please assign the issue to me if you don't mind.

**Comment by justinedelson** [comment]
Pretty sure this was done in 3.13.0. If not, please reopen.
