### ISSUE TITLE
Package which contains ACL entries can't be properly processed by the Package Replication Status Updater

### ISSUE THREAD

**Issue by salexb** [Adobe-Consulting-Services/acs-aem-commons#1327]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3 SP2
* [ ] ACS AEM Commons Version: 3.14.12

### Expected Behavior

When activating the attached package, leveraging [Package Replication Status Updater](https://adobe-consulting-services.github.io/acs-aem-commons/features/package-replication-status-updater/index.html), the package should be successfully activated without errors in a log and also replication properties should be set on activated content in author.

### Actual Behavior

The package is activated and available in publish instance but activating the attached package, or any other, which contains ACL entries, an exception is thrown and replication properties are not set for the content that is being activated.

### Steps to Reproduce

1. Login as an _admin_ user in CRX via /crx/packmgr/index.jsp
2. Upload the package attached and try to activate it.
3. Check error.log for the errors => javax.jcr.AccessDeniedException: Access denied is thrown.

Note that package has AC Handling set to MERGE under the _Advanced tab_ in a _Edit package_ dialog.

`12.04.2018 13:55:18.069 *ERROR* [sling-threadpool-ccd8f959-e24b-4861-a8f8-e6173395f99e-(apache-sling-job-thread-pool)-11-<main queue>(acs-commons/replication/package)] org.apache.jackrabbit.vault.fs.impl.io.DocViewSAXImporter Error while applying access control content.
javax.jcr.AccessDeniedException: Access denied.
	at org.apache.jackrabbit.oak.spi.security.authorization.accesscontrol.AbstractAccessControlManager.checkPermissions(AbstractAccessControlManager.java:200)
	at org.apache.jackrabbit.oak.spi.security.authorization.accesscontrol.AbstractAccessControlManager.getTree(AbstractAccessControlManager.java:167)
	at org.apache.jackrabbit.oak.spi.security.authorization.cug.impl.CugAccessControlManager.getCugPolicy(CugAccessControlManager.java:239)
	at org.apache.jackrabbit.oak.spi.security.authorization.cug.impl.CugAccessControlManager.getPolicies(CugAccessControlManager.java:99)
	at org.apache.jackrabbit.oak.security.authorization.composite.CompositeAccessControlManager.getPolicies(CompositeAccessControlManager.java:78)
	at org.apache.jackrabbit.oak.jcr.delegate.AccessControlManagerDelegator$5.perform(AccessControlManagerDelegator.java:97)
	at org.apache.jackrabbit.oak.jcr.delegate.AccessControlManagerDelegator$5.perform(AccessControlManagerDelegator.java:93)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:208)
	at org.apache.jackrabbit.oak.jcr.delegate.AccessControlManagerDelegator.getPolicies(AccessControlManagerDelegator.java:93)
	at org.apache.jackrabbit.oak.jcr.delegate.JackrabbitAccessControlManagerDelegator.getPolicies(JackrabbitAccessControlManagerDelegator.java:136)
	at org.apache.jackrabbit.vault.fs.impl.io.JackrabbitACLImporter$ImportedPolicy.getPolicy(JackrabbitACLImporter.java:192)
	at org.apache.jackrabbit.vault.fs.impl.io.JackrabbitACLImporter$ImportedAcList.apply(JackrabbitACLImporter.java:254)
	at org.apache.jackrabbit.vault.fs.impl.io.JackrabbitACLImporter.close(JackrabbitACLImporter.java:158)
	at org.apache.jackrabbit.vault.fs.impl.io.DocViewSAXImporter.endElement(DocViewSAXImporter.java:1154)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
	at org.apache.jackrabbit.vault.fs.impl.io.GenericArtifactHandler.accept(GenericArtifactHandler.java:99)
	at org.apache.jackrabbit.vault.fs.io.Importer.commit(Importer.java:896)
	at org.apache.jackrabbit.vault.fs.io.Importer.commit(Importer.java:801)
	at org.apache.jackrabbit.vault.fs.io.Importer.commit(Importer.java:841)
	at org.apache.jackrabbit.vault.fs.io.Importer.commit(Importer.java:841)
	at org.apache.jackrabbit.vault.fs.io.Importer.commit(Importer.java:841)
	at org.apache.jackrabbit.vault.fs.io.Importer.run(Importer.java:415)
	at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:234)
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:397)
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:356)
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:342)
	at com.adobe.acs.commons.packaging.impl.PackageHelperImpl.getContents(PackageHelperImpl.java:318)
	at com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler.setReplicationStatus(JcrPackageReplicationStatusEventHandler.java:258)
	at com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler.process(JcrPackageReplicationStatusEventHandler.java:240)`

### Links

[we-retail-test-failed.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1903472/we-retail-test-failed.zip)

@kwin fyi. Please add more info if needed.

**Comment by salexb** [comment]
Might be related to which permissions acs-commons-package-replication-status-event-service user has set on a root level. According to the [ACS Commons documentation](https://adobe-consulting-services.github.io/acs-aem-commons/features/package-replication-status-updater/index.html):

```
ACLs:
jcr:read, jcr:write on /
```

**Comment by kwin** [comment]
I think it makes sense to give this service user by default the right to dry-run install every possible package (even ones including policies). Don't know which rights are exactly necessary here though.

**Comment by kwin** [comment]
yes, as the service is only running on Author this happens on Author. After giving the user `acs-commons-package-replication-status-event-service` read-acl rights on root another exception is being thrown:
{code}
12.04.2018 16:26:46.699 *ERROR* [sling-threadpool-c6196050-761b-434c-bf14-c47059fb2c55-(apache-sling-job-thread-pool)-6-<main queue>(acs-commons/replication/package)] com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler RepositoryException occurred updating replication status for contents of package
javax.jcr.AccessDeniedException: OakAccess0000: Access denied
	at org.apache.jackrabbit.oak.api.CommitFailedException.asRepositoryException(CommitFailedException.java:231)
	at org.apache.jackrabbit.oak.api.CommitFailedException.asRepositoryException(CommitFailedException.java:212)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.newRepositoryException(SessionDelegate.java:670)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.save(SessionDelegate.java:496)
	at org.apache.jackrabbit.oak.jcr.session.SessionImpl$8.performVoid(SessionImpl.java:419)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.performVoid(SessionDelegate.java:274)
	at org.apache.jackrabbit.oak.jcr.session.SessionImpl.save(SessionImpl.java:416)
	at com.adobe.granite.repository.impl.CRX3SessionImpl.save(CRX3SessionImpl.java:208)
	at com.adobe.acs.commons.replication.status.impl.ReplicationStatusManagerImpl.setReplicationStatus(ReplicationStatusManagerImpl.java:163)
	at com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler.setReplicationStatus(JcrPackageReplicationStatusEventHandler.java:266)
	at com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler.process(JcrPackageReplicationStatusEventHandler.java:240)
	at org.apache.sling.event.impl.jobs.JobConsumerManager$JobConsumerWrapper.process(JobConsumerManager.java:500)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.startJob(JobQueueImpl.java:291)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.access$100(JobQueueImpl.java:58)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl$1.run(JobQueueImpl.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.jackrabbit.oak.api.CommitFailedException: OakAccess0000: Access denied
	at org.apache.jackrabbit.oak.security.authorization.permission.PermissionValidator.checkPermissions(PermissionValidator.java:242)
	at org.apache.jackrabbit.oak.security.authorization.permission.PermissionValidator.propertyChanged(PermissionValidator.java:128)
	at org.apache.jackrabbit.oak.spi.commit.VisibleValidator.propertyChanged(VisibleValidator.java:90)
	at org.apache.jackrabbit.oak.spi.commit.VisibleValidator.propertyChanged(VisibleValidator.java:90)
	at org.apache.jackrabbit.oak.spi.commit.VisibleValidator.propertyChanged(VisibleValidator.java:90)
	at org.apache.jackrabbit.oak.spi.commit.VisibleValidator.propertyChanged(VisibleValidator.java:90)
	at org.apache.jackrabbit.oak.spi.commit.VisibleValidator.propertyChanged(VisibleValidator.java:90)
	at org.apache.jackrabbit.oak.spi.commit.CompositeEditor.propertyChanged(CompositeEditor.java:91)
	at org.apache.jackrabbit.oak.spi.commit.EditorDiff.propertyChanged(EditorDiff.java:93)
	at org.apache.jackrabbit.oak.segment.SegmentNodeState.compareProperties(SegmentNodeState.java:621)
	at org.apache.jackrabbit.oak.segment.SegmentNodeState.compareAgainstBaseState(SegmentNodeState.java:515)
	at org.apache.jackrabbit.oak.spi.commit.EditorDiff.childNodeChanged(EditorDiff.java:148)
	at org.apache.jackrabbit.oak.segment.MapRecord.compare(MapRecord.java:490)
	at org.apache.jackrabbit.oak.segment.SegmentNodeState.compareAgainstBaseState(SegmentNodeState.java:608)
	at org.apache.jackrabbit.oak.spi.commit.EditorDiff.childNodeChanged(EditorDiff.java:148)
	at org.apache.jackrabbit.oak.segment.MapRecord.compare(MapRecord.java:490)
	at org.apache.jackrabbit.oak.segment.SegmentNodeState.compareAgainstBaseState(SegmentNodeState.java:608)
	at org.apache.jackrabbit.oak.spi.commit.EditorDiff.childNodeChanged(EditorDiff.java:148)
	at org.apache.jackrabbit.oak.segment.MapRecord$3.childNodeChanged(MapRecord.java:442)
	at org.apache.jackrabbit.oak.segment.MapRecord.compare(MapRecord.java:490)
	at org.apache.jackrabbit.oak.segment.MapRecord.compare(MapRecord.java:433)
	at org.apache.jackrabbit.oak.segment.SegmentNodeState.compareAgainstBaseState(SegmentNodeState.java:608)
	at org.apache.jackrabbit.oak.spi.commit.EditorDiff.childNodeChanged(EditorDiff.java:148)
	at org.apache.jackrabbit.oak.segment.MapRecord.compare(MapRecord.java:415)
	at org.apache.jackrabbit.oak.segment.SegmentNodeState.compareAgainstBaseState(SegmentNodeState.java:608)
	at org.apache.jackrabbit.oak.spi.commit.EditorDiff.childNodeChanged(EditorDiff.java:148)
	at org.apache.jackrabbit.oak.segment.MapRecord.compare(MapRecord.java:490)
	at org.apache.jackrabbit.oak.segment.SegmentNodeState.compareAgainstBaseState(SegmentNodeState.java:608)
	at org.apache.jackrabbit.oak.spi.commit.EditorDiff.process(EditorDiff.java:52)
	at org.apache.jackrabbit.oak.spi.commit.EditorHook.processCommit(EditorHook.java:55)
	at org.apache.jackrabbit.oak.spi.commit.CompositeHook.processCommit(CompositeHook.java:61)
	at org.apache.jackrabbit.oak.segment.SegmentNodeStore$Commit.prepare(SegmentNodeStore.java:604)
	at org.apache.jackrabbit.oak.segment.SegmentNodeStore$Commit.optimisticMerge(SegmentNodeStore.java:634)
	at org.apache.jackrabbit.oak.segment.SegmentNodeStore$Commit.execute(SegmentNodeStore.java:690)
	at org.apache.jackrabbit.oak.segment.SegmentNodeStore.merge(SegmentNodeStore.java:334)
	at org.apache.jackrabbit.oak.core.MutableRoot.commit(MutableRoot.java:249)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.commit(SessionDelegate.java:347)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.save(SessionDelegate.java:494)
	... 14 common frames omitted
{code}

**Comment by kwin** [comment]
Just for the record: Another non properly caught exception at FileVault has been reported at https://issues.apache.org/jira/browse/JCRVLT-287.
