### ISSUE TITLE
Package Replication Status Updater throws exceptions when version is being created in parallel

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#1409]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3.0.2
* [x] ACS AEM Commons Version: 3.17
* [x] Reproducible on Latest? yes/no

### Expected Behavior

The Sling Job to update the replication metadata after a package replication runs without exception

### Actual Behavior

From time to time the following exception is thrown:
```
26.06.2018 07:20:21.089 *ERROR* [sling-threadpool-f765411d-30df-47b2-8d0b-14fe5b522600-(apache-sling-job-thread-pool)-927-<main queue>(acs-commons/replication/package)] com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler Exception occurred updating replication status for contents of package '<some package>' covering paths '<some DAM paths>'
javax.jcr.version.VersionException: OakVersion0001: Cannot change property jcr:mixinTypes on checked in node
	at org.apache.jackrabbit.oak.api.CommitFailedException.asRepositoryException(CommitFailedException.java:241)
	at org.apache.jackrabbit.oak.api.CommitFailedException.asRepositoryException(CommitFailedException.java:212)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.newRepositoryException(SessionDelegate.java:670)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.save(SessionDelegate.java:496)
	at org.apache.jackrabbit.oak.jcr.session.SessionImpl$8.performVoid(SessionImpl.java:419)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.performVoid(SessionDelegate.java:274)
	at org.apache.jackrabbit.oak.jcr.session.SessionImpl.save(SessionImpl.java:416)
	at com.adobe.granite.repository.impl.CRX3SessionImpl.save(CRX3SessionImpl.java:208)
	at com.adobe.acs.commons.replication.status.impl.ReplicationStatusManagerImpl.setReplicationStatus(ReplicationStatusManagerImpl.java:181)
	at com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler.setReplicationStatus(JcrPackageReplicationStatusEventHandler.java:290)
	at com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler.process(JcrPackageReplicationStatusEventHandler.java:243)
	at org.apache.sling.event.impl.jobs.JobConsumerManager$JobConsumerWrapper.process(JobConsumerManager.java:500)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.startJob(JobQueueImpl.java:291)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.access$100(JobQueueImpl.java:58)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl$1.run(JobQueueImpl.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.jackrabbit.oak.api.CommitFailedException: OakVersion0001: Cannot change property jcr:mixinTypes on checked in node
	at org.apache.jackrabbit.oak.plugins.version.VersionEditor.throwCheckedIn(VersionEditor.java:250)
	at org.apache.jackrabbit.oak.plugins.version.VersionEditor.propertyChanged(VersionEditor.java:131)
```

This is due to the AEM default workflow `/etc/workflow/models/dam-xmp-writeback.html`, which implicitly creates asset versions in its {{XML Writeback}} step (`XMPWritebackProcess.writeXMP()`)

As JCR only allows modifications of checked out nodes, and nodes need to be checked in for a very short timeframe while creating a version, there should be the some retry mechanism in `JcrPackageReplicationStatusEventHandler` for this condition.

**Comment by kwin** [comment]
The Sling Jobs retry handling (https://sling.apache.org/documentation/bundles/apache-sling-eventing-and-job-handling.html#queue-configurations) should be used for those exceptions. Also there should be a dedicated queue configuration for the job topic `acs-commons/replication/package`.

**Comment by kwin** [comment]
@justinedelson Can you review the attached PR: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1411
