### ISSUE TITLE
Possible NPE in JcrPackageReplicationStatusEventHandler

### ISSUE THREAD

**Issue by tnebe** [Adobe-Consulting-Services/acs-aem-commons#1613]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.1
* [x] ACS AEM Commons Version: 3.18.2
* [x] Reproducible on Latest? yes

### Expected Behavior

On package activation, configured resource paths are set with a new replication status.

### Actual Behavior

In some cases a NPE in JcrPackageReplicationStatusEventHandler can prevent updating the replication status of configured resources.

NPE at `JcrPackageReplicationStatusEventHandler.java:399`

```
12.12.2018 09:58:17.258 *WARN* [Thread-26] org.apache.felix.eventadmin Service [com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler,4431, [org.apache.sling.event.jobs.consumer.JobConsumer, org.osgi.service.event.EventHandler, com.day.cq.jcrclustersupport.ClusterAware]] EventAdmin: Exception during event dispatch [org.osgi.service.event.Event [topic=com/day/cq/replication] {modificationDate=java.util.GregorianCalendar[time=1544608695369,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id="UTC",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2018,MONTH=11,WEEK_OF_YEAR=50,WEEK_OF_MONTH=3,DAY_OF_MONTH=12,DAY_OF_YEAR=346,DAY_OF_WEEK=4,DAY_OF_WEEK_IN_MONTH=2,AM_PM=0,HOUR=9,HOUR_OF_DAY=9,MINUTE=58,SECOND=15,MILLISECOND=369,ZONE_OFFSET=0,DST_OFFSET=0], type=ACTIVATE, userId=extern.nebe_tobias@allianz.de, paths=[Ljava.lang.String;@63481ef7} | [org.apache.sling.event.jobs.consumer.JobConsumer, org.osgi.service.event.EventHandler, com.day.cq.jcrclustersupport.ClusterAware] | Bundle(com.adobe.acs.acs-aem-commons-bundle [520])] (java.lang.NullPointerException)
        at com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler.getJcrPackage(JcrPackageReplicationStatusEventHandler.java:399) [com.adobe.acs.acs-aem-commons-bundle:3.18.2]
        at com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler.handleEvent(JcrPackageReplicationStatusEventHandler.java:214) [com.adobe.acs.acs-aem-commons-bundle:3.18.2]
```

### Links

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/c9f307eb60c8676ab8d737ffab4916d426a47932/bundle/src/main/java/com/adobe/acs/commons/replication/status/impl/JcrPackageReplicationStatusEventHandler.java#L384

**Comment by kwin** [comment]
I  guess this can only happen in case the `eventResource` is `null` in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/60987e8000479ccfcbd514b936a0d461e0a15668/bundle/src/main/java/com/adobe/acs/commons/replication/status/impl/JcrPackageReplicationStatusEventHandler.java#L399. The only other object which is dereferenced in that line is `packaging` which is a static service reference (i.e. cannot be null).
