### ISSUE TITLE
DispatcherFlushRules break replication in 6.4.2

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#1636]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.2
* [X] ACS AEM Commons Version: 3.17.0
* [X] Reproducible on Latest? ?

### Expected Behavior

Dispatcher Flush Rules should not break replication.

### Actual Behavior

Dispatcher Flush Rules break replication.

To fix the issue we remove all dispatcher flush rules

### Steps to Reproduce

```
*ERROR* [10.10.0.1 [1545238717730] POST /bin/replicate.json HTTP/1.1] com.day.cq.replication.impl.ReplicatorImpl Error while building replication content.
com.day.cq.replication.AccessDeniedException: Replicaiton Agent [flush1]- Agent user [null] doesn't have sufficient permission on [/content/geometrixx/(en/test)/jcr:content]
    at com.day.cq.replication.impl.ReplicatorImpl.buildContents(ReplicatorImpl.java:1010) [com.day.cq.cq-replication:6.2.46.CQ640-B0002]
    at com.day.cq.replication.impl.ReplicatorImpl.replicate(ReplicatorImpl.java:476) [com.day.cq.cq-replication:6.2.46.CQ640-B0002]
    at com.adobe.acs.commons.replication.dispatcher.impl.DispatcherFlusherImpl.flush(DispatcherFlusherImpl.java:106) [com.adobe.acs.acs-aem-commons-bundle:3.17.0]
    at com.adobe.acs.commons.replication.dispatcher.impl.DispatcherFlushRulesImpl.preprocess(DispatcherFlushRulesImpl.java:178) [com.adobe.acs.acs-aem-commons-bundle:3.17.0]
    at com.day.cq.replication.impl.ReplicatorImpl.replicate(ReplicatorImpl.java:463) [com.day.cq.cq-replication:6.2.46.CQ640-B0002]
    at com.day.cq.replication.impl.servlets.CommandServlet.doPost(CommandServlet.java:158) [com.day.cq.cq-replication:6.2.46.CQ640-B0002]
```

**Comment by davidjgonzalez** [comment]
Unable to reproduce and don't see how this use can be null (a LoginException should occur if the dispatcher-flush server user isn't available). Spoke w effected and they seem to have some workaround.

Putting this here for posterity: https://github.com/davidjgonzalez/acs-aem-commons/tree/feature/1636

This is branch adds extra debugging and adjusts the error handling (if a ReplicationException happens in the replicator.replicate(..) call its logged and swallowed, as to not prevent the entire replication.
IMO we should keep the feature operating as is (failing to replicate at all) if the rules fail, since these are logically all part of the same activity.

**Comment by kasyap1125** [comment]
@davidjgonzalez Will you be able to let me know what was the work around for this issue?

We have been facing the same issue and unable to find a work around for the same.

AEM: 6.3 (CPF - 6.3.3.2), ACS Commons (3.17.4)
