### ISSUE TITLE
generate-scr-metadata-for-unittests fails with error `java.lang.IncompatibleClassChangeError: Implementing class`

### ISSUE THREAD

**Issue by adamcin** [Adobe-Consulting-Services/acs-aem-commons#1675]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: **n/a**
* [ ] ACS AEM Commons Version: 3.19.1 (after [918fc6f](https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/918fc6fe420acbbd9bacd1b03536bc4a9e267233))
* [ ] Reproducible on Latest? yes (but only locally on my Mac, not in a docker container, and not on other dev's machines)

### Expected Behavior

The build should succeed with 
`mvn -s .travis.settings.xml clean verify` 
or 
`mvn -s .travis.settings.xml clean verify -Pskip-dependency-check -DskipTests`

### Actual Behavior

If I run a normal build, even after clearing my local m2 cache, I invariably hit this exception. (Interestingly, I don't encounter this exception when I run the same command but specify `-Dmaven.repo.local=$(pwd)/.repo` to force a different localRepository.)

This appears to be an understandable issue with embedding a `com.google.common.base.Suppliers` class from guava-27.0.1-jre, which defines SupplierFunction as an interface, that conflicts with the SupplierFunction enum type defined by the version of `com.google.common.base.Suppliers` embedded in uber-jar-6.3.0-apis, and the SCRPlugin fails to redefine SupplierFunction from enum to interface in order to load SupplierFunctionImpl which implements SupplierFunction.

```
[ERROR] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Got unexpected exception while analyzing:org.apache.felix.scrplugin.SCRDescriptorException: Unable to load compiled class: com.google.common.base.Suppliers$SupplierFunctionImpl
	at org.apache.felix.scrplugin.helper.ClassScanner.scanSources(ClassScanner.java:156)
	at org.apache.felix.scrplugin.SCRDescriptorGenerator.execute(SCRDescriptorGenerator.java:146)
	at org.apache.felix.scrplugin.bnd.SCRDescriptorBndPlugin.analyzeJar(SCRDescriptorBndPlugin.java:178)
	at aQute.bnd.osgi.Analyzer.doPlugins(Analyzer.java:820)
	at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:229)
	at aQute.bnd.osgi.Builder.analyze(Builder.java:408)
	at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:850)
	at aQute.bnd.osgi.Builder.build(Builder.java:116)
	at org.apache.felix.bundleplugin.ManifestPlugin.getAnalyzer(ManifestPlugin.java:291)
	at org.apache.felix.bundleplugin.ManifestPlugin.execute(ManifestPlugin.java:98)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:384)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:375)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.felix.scrplugin.helper.ClassScanner.scanSources(ClassScanner.java:144)
	... 33 more

[ERROR] Error(s) found in manifest configuration
```

### Steps to Reproduce

I haven't been able to get anyone else to reproduce this successfully. My specs:

```Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T11:41:47-07:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 1.8.0_192, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.2", arch: "x86_64", family: "mac"
```

**Comment by Sc0rpic0m** [comment]
I have this as well!

**Comment by Sc0rpic0m** [comment]
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 1.8.0_152, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.2", arch: "x86_64", family: "mac"

**Comment by joerghoh** [comment]
Runs without problems here:

```
Maven home: /usr/local/Cellar/maven/3.5.3/libexec
Java version: 1.8.0_172, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.2", arch: "x86_64", family: "mac"
```

The only difference is the maven version and JDK. I rather believe in Maven being the problem.

**Comment by adamcin** [comment]
@joerghoh I also had this issue with maven 3.5.2 and java _152. I have also tried adoptopenjdk.

**Comment by adamcin** [comment]
This is the log result of appending the scr bnd plugin options `                        <_plugin>org.apache.felix.scrplugin.bnd.SCRDescriptorBndPlugin;destdir=${project.build.outputDirectory};log=debug;logToFile=true</_plugin>` (specify `-Djava.io.tmpdir=/tmp` for the log file to appear at `/tmp/scrplugin/com.adobe.acs.acs-aem-commons-bundle.log`).

Notice that uber-jar is listed BEFORE guava in the `Using classpath:` line, but is listed after guava in the `Using dependencies:` line. @Sc0rpic0m @joerghoh can you both try adding this log config locally and reporting these values?

```
Thu 2019.01.10 10:33:16.245 - Info: Initialized Bnd ScrPlugin: destDir=/Users/madamcin/oss/acs-aem-commons/bundle/target/classes, strictMode=false, specVersion=null
Thu 2019.01.10 10:33:16.246 - Info: Analyzing com.adobe.acs.acs-aem-commons-bundle
Thu 2019.01.10 10:33:16.250 - Info: Using classpath: [file:/Users/madamcin/.m2/repository/org/ccil/cowan/tagsoup/tagsoup/1.2.1/tagsoup-1.2.1.jar, file:/Users/madamcin/.m2/repository/org/apache/sling/org.apache.sling.models.api/1.3.0/org.apache.sling.models.api-1.3.0.jar, file:/Users/madamcin/.m2/repository/commons-lang/commons-lang/2.5/commons-lang-2.5.jar, file:/Users/madamcin/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar, file:/Users/madamcin/.m2/repository/org/apache/tika/tika-core/1.14/tika-core-1.14.jar, file:/Users/madamcin/.m2/repository/org/apache/sling/org.apache.sling.servlets.annotations/1.0.0/org.apache.sling.servlets.annotations-1.0.0.jar, file:/Users/madamcin/.m2/repository/org/apache/httpcomponents/httpmime/4.5.2/httpmime-4.5.2.jar, file:/Users/madamcin/.m2/repository/org/apache/pdfbox/jempbox/1.8.4/jempbox-1.8.4.jar, file:/Users/madamcin/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar, file:/Users/madamcin/.m2/repository/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar, file:/Users/madamcin/.m2/repository/biz/aQute/bndlib/1.50.0/bndlib-1.50.0.jar, file:/Users/madamcin/oss/acs-aem-commons/bundle/target/classes/, file:/Users/madamcin/.m2/repository/javax/jcr/jcr/2.0/jcr-2.0.jar, file:/Users/madamcin/.m2/repository/org/bouncycastle/bcprov-jdk15/1.45/bcprov-jdk15-1.45.jar, file:/Users/madamcin/.m2/repository/com/adobe/aem/uber-jar/6.3.0/uber-jar-6.3.0-apis.jar, file:/Users/madamcin/.m2/repository/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar, file:/Users/madamcin/.m2/repository/org/gagravarr/vorbis-java-core/0.1/vorbis-java-core-0.1.jar, file:/Users/madamcin/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.4/jackson-annotations-2.8.4.jar, file:/Users/madamcin/.m2/repository/org/apache/james/apache-mime4j-dom/0.7.2/apache-mime4j-dom-0.7.2.jar, file:/Users/madamcin/.m2/repository/org/gagravarr/vorbis-java-tika/0.1/vorbis-java-tika-0.1.jar, file:/Users/madamcin/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar, file:/Users/madamcin/.m2/repository/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar, file:/Users/madamcin/.m2/repository/org/apache/pdfbox/fontbox/1.8.4/fontbox-1.8.4.jar, file:/Users/madamcin/.m2/repository/org/apache/xmlbeans/xmlbeans/2.3.0/xmlbeans-2.3.0.jar, file:/Users/madamcin/.m2/repository/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar, file:/Users/madamcin/.m2/repository/com/google/code/tld-generator/tld-generator/1.1/tld-generator-1.1.jar, file:/Users/madamcin/.m2/repository/org/twitter4j/twitter4j-core/3.0.6/twitter4j-core-3.0.6.jar, file:/Users/madamcin/.m2/repository/org/osgi/osgi.cmpn/6.0.0/osgi.cmpn-6.0.0.jar, file:/Users/madamcin/.m2/repository/com/jcraft/jsch/0.1.55/jsch-0.1.55.jar, file:/Users/madamcin/.m2/repository/io/jsonwebtoken/jjwt/0.9.1/jjwt-0.9.1.jar, file:/Users/madamcin/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.4/jackson-databind-2.8.4.jar, file:/Users/madamcin/.m2/repository/org/osgi/org.osgi.annotation/6.0.0/org.osgi.annotation-6.0.0.jar, file:/Users/madamcin/.m2/repository/org/apache/pdfbox/pdfbox/1.8.4/pdfbox-1.8.4.jar, file:/Users/madamcin/.m2/repository/org/tukaani/xz/1.2/xz-1.2.jar, file:/Users/madamcin/.m2/repository/org/antlr/antlr4-runtime/4.5.1-1/antlr4-runtime-4.5.1-1.jar, file:/Users/madamcin/.m2/repository/org/apache/commons/commons-compress/1.5/commons-compress-1.5.jar, file:/Users/madamcin/.m2/repository/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar, file:/Users/madamcin/.m2/repository/jdom/jdom/1.0/jdom-1.0.jar, file:/Users/madamcin/.m2/repository/org/osgi/org.osgi.util.promise/1.0.0/org.osgi.util.promise-1.0.0.jar, file:/Users/madamcin/.m2/repository/rome/rome/0.9/rome-0.9.jar, file:/Users/madamcin/.m2/repository/com/uwyn/jhighlight/1.0/jhighlight-1.0.jar, file:/Users/madamcin/.m2/repository/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar, file:/Users/madamcin/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar, file:/Users/madamcin/.m2/repository/org/scribe/scribe/1.3.0/scribe-1.3.0.jar, file:/Users/madamcin/.m2/repository/org/gagravarr/vorbis-java-core/0.1/vorbis-java-core-0.1-tests.jar, file:/Users/madamcin/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar, file:/Users/madamcin/.m2/repository/org/apache/httpcomponents/httpclient-osgi/4.5.2/httpclient-osgi-4.5.2.jar, file:/Users/madamcin/.m2/repository/org/apache/geronimo/specs/geronimo-stax-api_1.0_spec/1.0.1/geronimo-stax-api_1.0_spec-1.0.1.jar, file:/Users/madamcin/.m2/repository/org/apache/poi/poi/3.10-beta2/poi-3.10-beta2.jar, file:/Users/madamcin/.m2/repository/org/apache/felix/org.apache.felix.framework/4.6.1/org.apache.felix.framework-4.6.1.jar, file:/Users/madamcin/.m2/repository/com/github/ben-manes/caffeine/caffeine/2.6.2/caffeine-2.6.2.jar, file:/Users/madamcin/.m2/repository/org/apache/sling/org.apache.sling.api/2.16.0/org.apache.sling.api-2.16.0.jar, file:/Users/madamcin/.m2/repository/com/adobe/granite/com.adobe.granite.poi/2.0.6/com.adobe.granite.poi-2.0.6.jar, file:/Users/madamcin/.m2/repository/org/apache/poi/poi-ooxml/3.10-beta2/poi-ooxml-3.10-beta2.jar, file:/Users/madamcin/.m2/repository/com/adobe/cq/cq-dialog-conversion/1.0.2/cq-dialog-conversion-1.0.2.jar, file:/Users/madamcin/.m2/repository/org/aspectj/aspectjrt/1.6.11/aspectjrt-1.6.11.jar, file:/Users/madamcin/.m2/repository/org/osgi/osgi.core/6.0.0/osgi.core-6.0.0.jar, file:/Users/madamcin/.m2/repository/com/github/jknack/handlebars/4.0.6/handlebars-4.0.6.jar, file:/Users/madamcin/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar, file:/Users/madamcin/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar, file:/Users/madamcin/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.9/animal-sniffer-annotations-1.9.jar, file:/Users/madamcin/.m2/repository/org/bouncycastle/bcmail-jdk15/1.45/bcmail-jdk15-1.45.jar, file:/Users/madamcin/.m2/repository/org/apache/james/apache-mime4j-core/0.7.2/apache-mime4j-core-0.7.2.jar, file:/Users/madamcin/.m2/repository/org/apache/poi/poi-scratchpad/3.10-beta2/poi-scratchpad-3.10-beta2.jar, file:/Users/madamcin/.m2/repository/org/apache/httpcomponents/fluent-hc/4.5.2/fluent-hc-4.5.2.jar, file:/Users/madamcin/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar, file:/Users/madamcin/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar, file:/Users/madamcin/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.5.3/jackson-dataformat-cbor-2.5.3.jar, file:/Users/madamcin/.m2/repository/joda-time/joda-time/1.5.2/joda-time-1.5.2.jar, file:/Users/madamcin/.m2/repository/org/osgi/org.osgi.service.component/1.3.0/org.osgi.service.component-1.3.0.jar, file:/Users/madamcin/.m2/repository/org/apache/poi/poi-ooxml-schemas/3.10-beta2/poi-ooxml-schemas-3.10-beta2.jar, file:/Users/madamcin/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.4/jackson-core-2.8.4.jar, file:/Users/madamcin/.m2/repository/javax/servlet/jstl/1.1.1/jstl-1.1.1.jar, file:/Users/madamcin/.m2/repository/org/apache/tika/tika-parsers/1.5/tika-parsers-1.5.jar, file:/Users/madamcin/.m2/repository/org/mozilla/rhino/1.7R4/rhino-1.7R4.jar, file:/Users/madamcin/.m2/repository/javax/mail/mail/1.4.1/mail-1.4.1.jar, file:/Users/madamcin/.m2/repository/javax/servlet/jsp/jsp-api/2.1/jsp-api-2.1.jar, file:/Users/madamcin/.m2/repository/ch/qos/logback/logback-core/1.0.13/logback-core-1.0.13.jar, file:/Users/madamcin/.m2/repository/org/ow2/asm/asm-debug-all/4.1/asm-debug-all-4.1.jar, file:/Users/madamcin/.m2/repository/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.jar, file:/Users/madamcin/.m2/repository/com/jcraft/jzlib/1.1.3/jzlib-1.1.3.jar, file:/Users/madamcin/.m2/repository/org/apache/httpcomponents/httpclient-cache/4.5.2/httpclient-cache-4.5.2.jar, file:/Users/madamcin/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar, file:/Users/madamcin/.m2/repository/com/googlecode/mp4parser/isoparser/1.0-RC-1/isoparser-1.0-RC-1.jar, file:/Users/madamcin/.m2/repository/de/l3s/boilerpipe/boilerpipe/1.1.0/boilerpipe-1.1.0.jar, file:/Users/madamcin/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar, file:/Users/madamcin/.m2/repository/com/google/code/gson/gson/2.3/gson-2.3.jar, file:/Users/madamcin/.m2/repository/com/amazonaws/aws-java-sdk-osgi/1.10.76/aws-java-sdk-osgi-1.10.76.jar, file:/Users/madamcin/.m2/repository/org/apache/commons/commons-email/1.2/commons-email-1.2.jar, file:/Users/madamcin/.m2/repository/org/apache/felix/org.apache.felix.scr/1.8.2/org.apache.felix.scr-1.8.2.jar]
Thu 2019.01.10 10:33:16.251 - Info: Using dependencies: [/Users/madamcin/.m2/repository/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar, /Users/madamcin/.m2/repository/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar, /Users/madamcin/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar, /Users/madamcin/.m2/repository/org/apache/httpcomponents/httpclient-osgi/4.5.2/httpclient-osgi-4.5.2.jar, /Users/madamcin/.m2/repository/org/apache/httpcomponents/httpmime/4.5.2/httpmime-4.5.2.jar, /Users/madamcin/.m2/repository/org/apache/httpcomponents/httpclient-cache/4.5.2/httpclient-cache-4.5.2.jar, /Users/madamcin/.m2/repository/org/apache/httpcomponents/fluent-hc/4.5.2/fluent-hc-4.5.2.jar, /Users/madamcin/.m2/repository/org/osgi/osgi.cmpn/6.0.0/osgi.cmpn-6.0.0.jar, /Users/madamcin/.m2/repository/org/osgi/osgi.core/6.0.0/osgi.core-6.0.0.jar, /Users/madamcin/.m2/repository/biz/aQute/bndlib/1.50.0/bndlib-1.50.0.jar, /Users/madamcin/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar, /Users/madamcin/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar, /Users/madamcin/.m2/repository/javax/jcr/jcr/2.0/jcr-2.0.jar, /Users/madamcin/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar, /Users/madamcin/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar, /Users/madamcin/.m2/repository/commons-lang/commons-lang/2.5/commons-lang-2.5.jar, /Users/madamcin/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar, /Users/madamcin/.m2/repository/org/apache/commons/commons-email/1.2/commons-email-1.2.jar, /Users/madamcin/.m2/repository/javax/mail/mail/1.4.1/mail-1.4.1.jar, /Users/madamcin/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar, /Users/madamcin/.m2/repository/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar, /Users/madamcin/.m2/repository/joda-time/joda-time/1.5.2/joda-time-1.5.2.jar, /Users/madamcin/.m2/repository/javax/servlet/jsp/jsp-api/2.1/jsp-api-2.1.jar, /Users/madamcin/.m2/repository/javax/servlet/jstl/1.1.1/jstl-1.1.1.jar, /Users/madamcin/.m2/repository/org/scribe/scribe/1.3.0/scribe-1.3.0.jar, /Users/madamcin/.m2/repository/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar, /Users/madamcin/.m2/repository/ch/qos/logback/logback-core/1.0.13/logback-core-1.0.13.jar, /Users/madamcin/.m2/repository/com/adobe/cq/cq-dialog-conversion/1.0.2/cq-dialog-conversion-1.0.2.jar, /Users/madamcin/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar, /Users/madamcin/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar, /Users/madamcin/.m2/repository/com/google/code/gson/gson/2.3/gson-2.3.jar, /Users/madamcin/.m2/repository/org/apache/felix/org.apache.felix.scr/1.8.2/org.apache.felix.scr-1.8.2.jar, /Users/madamcin/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.9/animal-sniffer-annotations-1.9.jar, /Users/madamcin/.m2/repository/org/osgi/org.osgi.service.component/1.3.0/org.osgi.service.component-1.3.0.jar, /Users/madamcin/.m2/repository/org/osgi/org.osgi.util.promise/1.0.0/org.osgi.util.promise-1.0.0.jar, /Users/madamcin/.m2/repository/org/apache/felix/org.apache.felix.framework/4.6.1/org.apache.felix.framework-4.6.1.jar, /Users/madamcin/.m2/repository/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.jar, /Users/madamcin/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar, /Users/madamcin/.m2/repository/com/adobe/granite/com.adobe.granite.poi/2.0.6/com.adobe.granite.poi-2.0.6.jar, /Users/madamcin/.m2/repository/org/apache/tika/tika-core/1.14/tika-core-1.14.jar, /Users/madamcin/.m2/repository/org/apache/tika/tika-parsers/1.5/tika-parsers-1.5.jar, /Users/madamcin/.m2/repository/org/gagravarr/vorbis-java-tika/0.1/vorbis-java-tika-0.1.jar, /Users/madamcin/.m2/repository/org/gagravarr/vorbis-java-core/0.1/vorbis-java-core-0.1-tests.jar, /Users/madamcin/.m2/repository/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar, /Users/madamcin/.m2/repository/org/apache/james/apache-mime4j-core/0.7.2/apache-mime4j-core-0.7.2.jar, /Users/madamcin/.m2/repository/org/apache/james/apache-mime4j-dom/0.7.2/apache-mime4j-dom-0.7.2.jar, /Users/madamcin/.m2/repository/org/apache/commons/commons-compress/1.5/commons-compress-1.5.jar, /Users/madamcin/.m2/repository/org/tukaani/xz/1.2/xz-1.2.jar, /Users/madamcin/.m2/repository/org/apache/pdfbox/pdfbox/1.8.4/pdfbox-1.8.4.jar, /Users/madamcin/.m2/repository/org/apache/pdfbox/fontbox/1.8.4/fontbox-1.8.4.jar, /Users/madamcin/.m2/repository/org/apache/pdfbox/jempbox/1.8.4/jempbox-1.8.4.jar, /Users/madamcin/.m2/repository/org/bouncycastle/bcmail-jdk15/1.45/bcmail-jdk15-1.45.jar, /Users/madamcin/.m2/repository/org/bouncycastle/bcprov-jdk15/1.45/bcprov-jdk15-1.45.jar, /Users/madamcin/.m2/repository/org/apache/poi/poi/3.10-beta2/poi-3.10-beta2.jar, /Users/madamcin/.m2/repository/org/apache/poi/poi-scratchpad/3.10-beta2/poi-scratchpad-3.10-beta2.jar, /Users/madamcin/.m2/repository/org/apache/poi/poi-ooxml/3.10-beta2/poi-ooxml-3.10-beta2.jar, /Users/madamcin/.m2/repository/org/apache/poi/poi-ooxml-schemas/3.10-beta2/poi-ooxml-schemas-3.10-beta2.jar, /Users/madamcin/.m2/repository/org/apache/xmlbeans/xmlbeans/2.3.0/xmlbeans-2.3.0.jar, /Users/madamcin/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar, /Users/madamcin/.m2/repository/org/apache/geronimo/specs/geronimo-stax-api_1.0_spec/1.0.1/geronimo-stax-api_1.0_spec-1.0.1.jar, /Users/madamcin/.m2/repository/org/ccil/cowan/tagsoup/tagsoup/1.2.1/tagsoup-1.2.1.jar, /Users/madamcin/.m2/repository/org/ow2/asm/asm-debug-all/4.1/asm-debug-all-4.1.jar, /Users/madamcin/.m2/repository/com/googlecode/mp4parser/isoparser/1.0-RC-1/isoparser-1.0-RC-1.jar, /Users/madamcin/.m2/repository/org/aspectj/aspectjrt/1.6.11/aspectjrt-1.6.11.jar, /Users/madamcin/.m2/repository/de/l3s/boilerpipe/boilerpipe/1.1.0/boilerpipe-1.1.0.jar, /Users/madamcin/.m2/repository/rome/rome/0.9/rome-0.9.jar, /Users/madamcin/.m2/repository/jdom/jdom/1.0/jdom-1.0.jar, /Users/madamcin/.m2/repository/org/gagravarr/vorbis-java-core/0.1/vorbis-java-core-0.1.jar, /Users/madamcin/.m2/repository/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar, /Users/madamcin/.m2/repository/com/uwyn/jhighlight/1.0/jhighlight-1.0.jar, /Users/madamcin/.m2/repository/com/amazonaws/aws-java-sdk-osgi/1.10.76/aws-java-sdk-osgi-1.10.76.jar, /Users/madamcin/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.5.3/jackson-dataformat-cbor-2.5.3.jar, /Users/madamcin/.m2/repository/com/jcraft/jsch/0.1.55/jsch-0.1.55.jar, /Users/madamcin/.m2/repository/com/jcraft/jzlib/1.1.3/jzlib-1.1.3.jar, /Users/madamcin/.m2/repository/org/twitter4j/twitter4j-core/3.0.6/twitter4j-core-3.0.6.jar, /Users/madamcin/.m2/repository/com/github/ben-manes/caffeine/caffeine/2.6.2/caffeine-2.6.2.jar, /Users/madamcin/.m2/repository/org/apache/sling/org.apache.sling.models.api/1.3.0/org.apache.sling.models.api-1.3.0.jar, /Users/madamcin/.m2/repository/com/github/jknack/handlebars/4.0.6/handlebars-4.0.6.jar, /Users/madamcin/.m2/repository/org/antlr/antlr4-runtime/4.5.1-1/antlr4-runtime-4.5.1-1.jar, /Users/madamcin/.m2/repository/org/mozilla/rhino/1.7R4/rhino-1.7R4.jar, /Users/madamcin/.m2/repository/com/adobe/aem/uber-jar/6.3.0/uber-jar-6.3.0-apis.jar, /Users/madamcin/.m2/repository/io/jsonwebtoken/jjwt/0.9.1/jjwt-0.9.1.jar, /Users/madamcin/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.4/jackson-databind-2.8.4.jar, /Users/madamcin/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.4/jackson-core-2.8.4.jar, /Users/madamcin/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.4/jackson-annotations-2.8.4.jar, /Users/madamcin/.m2/repository/org/apache/sling/org.apache.sling.servlets.annotations/1.0.0/org.apache.sling.servlets.annotations-1.0.0.jar, /Users/madamcin/.m2/repository/org/apache/sling/org.apache.sling.api/2.16.0/org.apache.sling.api-2.16.0.jar, /Users/madamcin/.m2/repository/org/osgi/org.osgi.annotation/6.0.0/org.osgi.annotation-6.0.0.jar, /Users/madamcin/.m2/repository/com/google/code/tld-generator/tld-generator/1.1/tld-generator-1.1.jar]
Thu 2019.01.10 10:33:16.275 - Debug: Starting SCR Descriptor Generator....
Thu 2019.01.10 10:33:16.275 - Debug: ..using output directory: /Users/madamcin/oss/acs-aem-commons/bundle/target/classes
Thu 2019.01.10 10:33:16.275 - Debug: ..strict mode: false
Thu 2019.01.10 10:33:16.275 - Debug: ..generating accessors: true
Thu 2019.01.10 10:33:16.275 - Debug: ..auto detecting spec version
Thu 2019.01.10 10:33:16.296 - Debug: ..using annotation processors:
Thu 2019.01.10 10:33:16.296 - Debug:   - Apache Sling Annotation Processor - 500
Thu 2019.01.10 10:33:16.296 - Debug:   - Apache Felix SCR Annotation Processor - 1000
```

**Comment by adamcin** [comment]
I found it. It appears to be a bug in org.apache.felix.scr.bnd's SCRDescriptorBndPlugin where the Analyzer classpath is passed through a non-linked HashSet, thus introducing an unspecified ordering on the classpath elements: https://github.com/apache/felix/blob/trunk/tools/org.apache.felix.scr.bnd/src/main/java/org/apache/felix/scrplugin/bnd/SCRDescriptorBndPlugin.java#L302

I changed this to a LinkedHashSet locally in the felix source and rebuilt org.apache.felix.scr.bnd, and the exception disappeared.

I'll see about filing a bug with the Felix project, but it's still a non-deterministic bug in acs-aem-commons master.

**Comment by adamcin** [comment]
Reported to Felix: https://issues.apache.org/jira/browse/FELIX-6023

**Comment by adamcin** [comment]
@Sc0rpic0m so here is my attempt at a workaround until we can get the felix patch merged. Since the issue is the unspecified ordering of the classpath elements in a HashSet, it appears that overriding the local maven repository with `-Dmaven.repo.local` can force a different random ordering. So you have to move your m2 cache around until the hashCodes of the URLs for your maven dependency files all end up coming out of the HashSet iterator in the right order so that uber-jar comes after guava on the bnd plugin classpath. I found that this command works for me: `mvn -s .travis.settings.xml clean verify -Pskip-dependency-check -DskipTests -Dmaven.repo.local=$(pwd)/../fresh-acs/.repo`.

**Comment by badvision** [comment]
Ultimately our goal is to remove SCR entirely.  Do you mind if we close this for now?

**Comment by kwin** [comment]
I am also running into this. I will try to get someone to release the fixed scr bnd plugin.
