### ISSUE TITLE
S3,FileAssetIngestorTests fail with UnsupportedOperationException on JCR_MOCK

### ISSUE THREAD

**Issue by adamcin** [Adobe-Consulting-Services/acs-aem-commons#1694]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: n/a
* [ ] ACS AEM Commons Version: 101ba2e23bcc37312a6e8f0a418ae0425a5e1303
* [ ] Reproducible on Latest? yes

### Expected Behavior

Build should succeed.

### Actual Behavior

Two tests are failing because the MockSession from JCR_MOCK throws an UnsupportedOperationException when `refresh(keepChanges = false)` is called (which seems like an exception a mock type should never throw, IMO).

```
[ERROR] Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.226 s <<< FAILURE! - in com.adobe.acs.commons.mcp.impl.processes.asset.S3AssetIngestorTest
[ERROR] testImportAssetsWithException(com.adobe.acs.commons.mcp.impl.processes.asset.S3AssetIngestorTest)  Time elapsed: 0.189 s  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<com.adobe.acs.commons.mcp.impl.processes.asset.AssetIngestorException> but was<java.lang.UnsupportedOperationException>
	at com.adobe.acs.commons.mcp.impl.processes.asset.S3AssetIngestorTest.testImportAssetsWithException(S3AssetIngestorTest.java:214)
```
and
```
[ERROR] Tests run: 13, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.058 s <<< FAILURE! - in com.adobe.acs.commons.mcp.impl.processes.asset.FileAssetIngestorTest
[ERROR] testImportAssetsWithException(com.adobe.acs.commons.mcp.impl.processes.asset.FileAssetIngestorTest)  Time elapsed: 0.05 s  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<com.adobe.acs.commons.mcp.impl.processes.asset.AssetIngestorException> but was<java.lang.UnsupportedOperationException>
	at com.adobe.acs.commons.mcp.impl.processes.asset.FileAssetIngestorTest.lambda$setup$0(FileAssetIngestorTest.java:121)
	at com.adobe.acs.commons.mcp.impl.processes.asset.FileAssetIngestorTest.lambda$setup$0(FileAssetIngestorTest.java:121)
	at com.adobe.acs.commons.mcp.impl.processes.asset.FileAssetIngestorTest.testImportAssetsWithException(FileAssetIngestorTest.java:233)
```

I dumped the stacktrace for the UnsupportedOperationException:

```
java.lang.UnsupportedOperationException
	at org.apache.sling.testing.mock.jcr.MockSession.refresh(MockSession.java:341)
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.revert(JcrResourceProvider.java:470)
	at org.apache.sling.resourceresolver.impl.providers.stateful.AuthenticatedResourceProvider.revert(AuthenticatedResourceProvider.java:205)
	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.revert(ResourceResolverControl.java:402)
	at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.revert(ResourceResolverImpl.java:1216)
	at com.adobe.acs.commons.fam.actions.Actions.lambda$retry$2(Actions.java:153)
	at com.adobe.acs.commons.mcp.impl.processes.asset.S3AssetIngestorTest$2.answer(S3AssetIngestorTest.java:128)
	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:34)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
	at org.powermock.api.mockito.repackaged.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:60)
	at com.adobe.acs.commons.fam.ActionManager$$EnhancerByMockitoWithCGLIB$$d50a591.deferredWithResolver(<generated>)
	at com.adobe.acs.commons.mcp.impl.processes.asset.S3AssetIngestor.lambda$importAssets$7(S3AssetIngestor.java:154)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.adobe.acs.commons.mcp.impl.processes.asset.S3AssetIngestor.importAssets(S3AssetIngestor.java:151)
	at com.adobe.acs.commons.mcp.impl.processes.asset.S3AssetIngestor.lambda$importAssets$5(S3AssetIngestor.java:144)
	at com.adobe.acs.commons.mcp.impl.processes.asset.S3AssetIngestorTest$2.answer(S3AssetIngestorTest.java:128)
	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:34)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
	at org.powermock.api.mockito.repackaged.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:60)
	at com.adobe.acs.commons.fam.ActionManager$$EnhancerByMockitoWithCGLIB$$d50a591.deferredWithResolver(<generated>)
	at com.adobe.acs.commons.mcp.impl.processes.asset.S3AssetIngestor.importAssets(S3AssetIngestor.java:140)
	at com.adobe.acs.commons.mcp.impl.processes.asset.S3AssetIngestorTest.testImportAssetsWithException(S3AssetIngestorTest.java:215)
```

### Steps to Reproduce

Checkout above commit and run `mvn test -Dtest=S3AssetIngestorTest`.

### Links

Found the related SLING issue that introduced this exception for MockSession: [SLING-7692](https://issues.apache.org/jira/browse/SLING-7692). Read for background.

**Comment by joerghoh** [comment]
good finding, thanks @adamcin 

But I wonder why #1689 hasn't failed as well (where I introduced this). I also tested locally and everything was fine. Strange ...

**Comment by adamcin** [comment]
@joerghoh your PR was built before #1678 had been merged, which introduced the test that started failing only after YOUR PR was merged: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1678/files#diff-cf2c630fc27e3c6332c6935156de149dR227
