### ISSUE TITLE
All CacheMBeans produce stack trace on startup

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#1747]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3
* [x] ACS AEM Commons Version: release/4.x branch
* [x] Reproducible on Latest? assume yes

### Expected Behavior

Upon installation of the bundle, multiple of these stack traces are produced:

```
java.lang.ClassNotFoundException: [Ljava.lang.String; not found by com.adobe.acs.acs-aem-commons-bundle [521]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1574)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.adobe.granite.jmx.internal.Utils.loadClass(Utils.java:52)
	at com.adobe.granite.jmx.annotation.AnnotatedStandardMBean.getMethod(AnnotatedStandardMBean.java:282)
	at com.adobe.granite.jmx.annotation.AnnotatedStandardMBean.getImpact(AnnotatedStandardMBean.java:155)
	at javax.management.StandardMBean.getOperations(StandardMBean.java:1007)
	at javax.management.StandardMBean.getMBeanInfo(StandardMBean.java:459)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getNewMBeanClassName(DefaultMBeanServerInterceptor.java:333)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:319)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.aries.jmx.whiteboard.MBeanHolder.register(MBeanHolder.java:114)
	at org.apache.aries.jmx.whiteboard.JmxWhiteboardSupport.registerMBean(JmxWhiteboardSupport.java:86)
	at org.apache.aries.jmx.whiteboard.Activator$MBeanTracker.addingService(Activator.java:102)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:991)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:839)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:546)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4558)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3550)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
```

### Actual Behavior

Installation should not produce stack traces in log

### Steps to Reproduce

1. Install bundle.
2. Watch log

### Links

This was caused by https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/720a9fed075ff559063a141b159d4b80beae33ee and specifically the introduction of `DyanmicMBean` as a super-interface on `CacheMBean`

**Comment by justinedelson** [comment]
@niekraaijmakers can you explain why `DynamicMBean` was added as a super-interface?

**Comment by niekraaijmakers** [comment]
Well, I thought to make it clear (name / responsibility wise) that this is an DynamicMBean.. but I didn't know it would cause these issues. I think I have an idea but il talk to David why this exactly occurs, so I know better next time.

**Comment by justinedelson** [comment]
But these aren't DynamicMBeans -- they are StandardMBeans. That's the problem -- you can't have a StandardMBean also be a DynamicMBean.

**Comment by niekraaijmakers** [comment]
Auch :( Your right
