### ISSUE TITLE
folder creator - cannot create numeric folder

### ISSUE THREAD

**Issue by aaantoine** [Adobe-Consulting-Services/acs-aem-commons#1791]
## Required Information

* [ 6.4.3] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [3.19.0 ] ACS AEM Commons Version: _____
* [yes] Reproducible on Latest? yes/no

### Expected Behavior

I provide a excel file with some folders alphanumeric ( for example :  2018), I expect that the folder 2018 is created
### Actual Behavior

The folder is not created and an exception is raised : 

2019-03-18 15:04:22 |   | Cannot get a STRING value from a NUMERIC cell | java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:1062) at org.apache.poi.xssf.usermodel.XSSFCell.getRichStringCellValue(XSSFCell.java:395) at org.apache.poi.xssf.usermodel.XSSFCell.getStringCellValue(XSSFCell.java:347) at com.adobe.acs.commons.mcp.impl.processes.AssetFolderCreator.parseAssetFolderCell(AssetFolderCreator.java:188) at com.adobe.acs.commons.mcp.impl.processes.AssetFolderCreator.parseAssetFolderRow(AssetFolderCreator.java:170) at com.adobe.acs.commons.mcp.impl.processes.AssetFolderCreator.lambda$parseAssetFolderDefinitions$0(AssetFolderCreator.java:151) at com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:214) at com.adobe.acs.commons.mcp.impl.processes.AssetFolderCreator.parseAssetFolderDefinitions(AssetFolderCreator.java:142) at com.adobe.acs.commons.mcp.impl.ProcessInstanceImpl.lambda$runStep$14(ProcessInstanceImpl.java:235) at com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:214) at com.adobe.acs.commons.fam.impl.ActionManagerImpl.runActionAndLogErrors(ActionManagerImpl.java:176) at com.adobe.acs.commons.fam.impl.ActionManagerImpl.lambda$deferredWithResolver$0(ActionManagerImpl.java:168) at com.adobe.acs.commons.fam.impl.TimedRunnable.run(TimedRunnable.java:88) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
-- | -- | -- | --

### Steps to Reproduce
Upload an excel file with the value 2018 in a row, and launch the folder creator with this excel file, Lowercase With Dashes as primary creator
_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by davidjgonzalez** [comment]
Thanks @aaantoine - should be fixed in: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1792
