### ISSUE TITLE
DialogResourceProviderFactoryImpl slows down bundle deployment

### ISSUE THREAD

**Issue by cnagel** [Adobe-Consulting-Services/acs-aem-commons#1979]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5
* [ ] ACS AEM Commons Version: 4.2
* [ ] Reproducible on Latest? yes

### Expected Behavior

ACS Commons should not slow down Bundle deployment.

### Actual Behavior

When ACS Commons 4.2 is installed, the deployment of a bundle with many Sling Models is very slow. The log shows multiple entries:
```
1478	Thu Jul 04 09:10:45 CEST 2019	INFO	Service [7206, [org.apache.sling.adapter.Adaption]] ServiceEvent UNREGISTERING	ClassWrapper{className='org.apache.sling.adapter'}	OsgiInstallerImpl		Note [note=]
1479	Thu Jul 04 09:10:45 CEST 2019	INFO	Service [7207, [org.apache.sling.api.adapter.AdapterFactory]] ServiceEvent UNREGISTERING	ClassWrapper{className='org.apache.sling.models.impl'}	OsgiInstallerImpl		Note [note=]
1480	Thu Jul 04 09:10:45 CEST 2019	INFO	Service [com.adobe.acs.commons.mcp.impl.DialogResourceProviderFactoryImpl,12540, [com.adobe.acs.commons.mcp.DialogResourceProviderFactory]] ServiceEvent UNREGISTERING	ClassWrapper{className='com.adobe.acs.acs-aem-commons-bundle'}	OsgiInstallerImpl		Note [note=]
1481	Thu Jul 04 09:10:45 CEST 2019	INFO	Service [com.adobe.acs.commons.mcp.impl.DialogResourceProviderFactoryImpl,12541, [com.adobe.acs.commons.mcp.DialogResourceProviderFactory]] ServiceEvent REGISTERED	ClassWrapper{className='com.adobe.acs.acs-aem-commons-bundle'}	OsgiInstallerImpl		Note [note=]
1482	Thu Jul 04 09:10:45 CEST 2019	INFO	This service is no longer functional (PreferencesServiceFactory).	ClassWrapper{className='com.day.cq.preferences.PreferencesServiceFactory'}	OsgiInstallerImpl		Note [note=]
```
For each time a Sling Model gets activated, the DialogResourceProviderFactoryImpl gets deactivated and activated again. Looking into the code it looks like the static greedy [AdapterFactory Reference](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/7ce9ba871a5da97abaf1c84a7871df74d9995d10/bundle/src/main/java/com/adobe/acs/commons/mcp/impl/DialogResourceProviderFactoryImpl.java#L74) should be the cause of this behaviour.

### Steps to Reproduce
* Start AEM 6.5 Vanilla
* Install ACS Commons 4.2
* Install a bundle with many Sling Models
* Redeploy bundle

**Comment by henrykuijpers** [comment]
I'm seeing this also!

Log is full with:
{code}
com.day.cq.preferences.PreferencesServiceFactory This service is no longer functional (PreferencesServiceFactory).
09.07.2019 18:18:54.525 *INFO* [Background Update x (563)] org.apache.sling.adapter Service [14540, [org.apache.sling.adapter.Adaption]] ServiceEvent UNREGISTERING
09.07.2019 18:18:54.527 *INFO* [Background Update x (563)] org.apache.sling.models.impl Service [14538, [org.apache.sling.api.adapter.AdapterFactory]] ServiceEvent UNREGISTERING
09.07.2019 18:18:54.529 *INFO* [Background Update x (563)] com.adobe.acs.acs-aem-commons-bundle Service [com.adobe.acs.commons.mcp.impl.DialogResourceProviderFactoryImpl,17897, [com.adobe.acs.commons.mcp.DialogResourceProviderFactory]] ServiceEvent UNREGISTERING
09.07.2019 18:18:54.533 *INFO* [Background Update x (563)] com.adobe.acs.acs-aem-commons-bundle Service [com.adobe.acs.commons.mcp.impl.DialogResourceProviderFactoryImpl,17898, [com.adobe.acs.commons.mcp.DialogResourceProviderFactory]] ServiceEvent REGISTERED
09.07.2019 18:18:54.534 *INFO* [Background Update x (563)] com.day.cq.preferences.PreferencesServiceFactory
{code}

And:
{code}
09.07.2019 18:23:15.735 *ERROR* [Background Update x (563)] ERROR: Bundle '565' EventDispatcher: Error during dispatch. (java.lang.IllegalStateException: The service registration is no longer valid.)
java.lang.IllegalStateException: The service registration is no longer valid.
	at org.apache.felix.framework.ServiceRegistrationImpl.getReference(ServiceRegistrationImpl.java:108)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:745)
	at org.apache.felix.scr.impl.manager.ExtendedServiceEvent.activateManagers(ExtendedServiceEvent.java:59)
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:142)
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4595)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3587)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:891)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:877)
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:944)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:727)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:661)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:427)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:665)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:339)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:381)
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:49)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:263)
	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:415)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2174)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.webconsole.internal.core.BaseUpdateInstallHelper.run(BaseUpdateInstallHelper.java:192)
	at java.lang.Thread.run(Thread.java:748)
{code}

{code}
09.07.2019 18:23:54.606 *WARN* [Background Update x (563)] com.adobe.acs.acs-aem-commons-bundle bundle com.adobe.acs.acs-aem-commons-bundle:4.2.0 (565)[com.adobe.acs.commons.mcp.impl.DialogResourceProviderFactoryImpl(4204)] :  Component deactivation threw an exception (java.lang.IllegalStateException: Could not obtain lock)
java.lang.IllegalStateException: Could not obtain lock
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.obtainLock(AbstractComponentManager.java:235) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.obtainStateLock(AbstractComponentManager.java:282) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.doDeactivate(AbstractComponentManager.java:812) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.deactivateInternal(AbstractComponentManager.java:790) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.DependencyManager.deactivateComponentManager(DependencyManager.java:2328) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.DependencyManager.access$400(DependencyManager.java:56) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleStaticGreedyCustomizer.addedService(DependencyManager.java:494) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleStaticGreedyCustomizer.addedService(DependencyManager.java:472) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1216) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1137) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:944) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:880) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1168) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:125) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4595)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3587)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:891) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:877) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:944) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:727) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:661) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:427) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:665) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:339) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:381) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:49) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:263) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49) [org.apache.felix.scr:2.1.0.B008]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482) [org.apache.felix.eventadmin:1.4.10]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:415) [org.apache.felix.eventadmin:1.4.10]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) [org.apache.felix.eventadmin:1.4.10]
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444) [org.apache.felix.eventadmin:1.4.10]
	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2174)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.webconsole.internal.core.BaseUpdateInstallHelper.run(BaseUpdateInstallHelper.java:192) [org.apache.felix.webconsole:4.3.8]
	at java.lang.Thread.run(Thread.java:748)
{code}

**Comment by badvision** [comment]
Right, the sling model factories get blown away and recreated upstream.  Since this service monitors those it gets a full list of them each time -- is there a better way to register the service so the product isn't bombarding it?

**Comment by henrykuijpers** [comment]
Hi @davidjgonzalez , I see that you modified the milestone of this ticket to 4.2.2, which was released 7 hours ago. However, I don't see this issue mentioned in the release notes? Does that mean it was not fixed in that release?

**Comment by davidjgonzalez** [comment]
@henrykuijpers i modified it to 4.2.4 (from 4.2.2) -- i don't think this was fixed yet? Is there a PR for this? Is this active by default? Are you using this feature - or did you start getting this performance hits just by installing 4.2.0+?

**Comment by davidjgonzalez** [comment]
@badvision confirming that this feature is "Disabled by default" and this performance issue is ONLY when someone has chosen to use this feature.

**Comment by badvision** [comment]
The dialogs resource provides are not registered unless the feature is enabled, however it still has to track registration of models; is it possible this is just a binding issue?

**Comment by davidjgonzalez** [comment]
@badvision so, the thing causing the slowness (tracking the model registration) is "on by default". Can this be disabled by default, as is the convention for ACS Commons features, and only tracks registration if someone explicitly turns this feature on?

**Comment by davidjgonzalez** [comment]
@cnagel @henrykuijpers - https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1992 should fix this.

Looking through this code, there are 2 areas that are worth looking at that are not in this PR:

1) using OSGi to filter out AdapterFactories to handle .. `(&(!(models.adapter.implementationClass=com.adobe.cq.*))(!(models.adapter.implementationClass=com.adobe.aemds.*))
..etc..) 
2) Im not sure if there will be issues with the class lookup is the class is in a different bundle; I typically use the DynamicClassLoader for that.

**Comment by badvision** [comment]
@cnagel, @henrykuijpers does the mentioned code change from @davidjgonzalez resolve the issue you were seeing?

**Comment by henrykuijpers** [comment]
I'll have to find some time tomorrow to check this out, pretty busy working on multiple projects these days. I'll update this ticket as soon as possible.

**Comment by cnagel** [comment]
@badvision Yes, redeployment of our bundle with ACS Commons 4.2.3-SNAPSHOT works fast.
Log is not flooded with the described messages.
Thanks.

**Comment by davidjgonzalez** [comment]
We should try to cut a release with this ASAP; offline someone else reached out to me reporting they are experiencing these performance issues as well and it's preventing them from deploying the updated ACS Commons to production.

**Comment by badvision** [comment]
I have another fix going in, give me a couple of hours to test.

**Comment by DavidAtWorking** [comment]
Hi, it looks like in version 4.3 it comes back again. The code is in commit 0ffd40a . The class
DialogResourceProviderFactoryImpl.java put all the adapter factory register and unregister things back. Any particular reason to do this?
