### ISSUE TITLE
MCP Processes fail to start due to missing page

### ISSUE THREAD

**Issue by shsteimer** [Adobe-Consulting-Services/acs-aem-commons#2063]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.0.0
* [ ] ACS AEM Commons Version: 4.3.3-SANPSHOT (master)
* [ ] Reproducible on Latest? yes

### Expected Behavior

The MCP Process should run.

### Actual Behavior

The process fails to run and the ui spins with no indication of an error.

### Steps to Reproduce

Start any MCP process.  The ui will spin and nothing will happen.  In the log you will see the following stack trace

`
30.09.2019 10:55:04.633 *INFO* [0:0:0:0:0:0:0:1 [1569866104631] GET /etc/acs-commons/manage-controlled-processes/jcr:content.list.json HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Resource /etc/acs-commons/manage-controlled-processes/jcr:content.list.json not found
30.09.2019 10:55:11.584 *ERROR* [0:0:0:0:0:0:0:1 [1569866111581] POST /etc/acs-commons/manage-controlled-processes/jcr:content.start.json HTTP/1.1] org.apache.sling.servlets.post.impl.operations.ModifyOperation Unable to create resource named manage-controlled-processes in /etc/acs-commons
30.09.2019 10:55:11.585 *ERROR* [0:0:0:0:0:0:0:1 [1569866111581] POST /etc/acs-commons/manage-controlled-processes/jcr:content.start.json HTTP/1.1] org.apache.sling.servlets.post.impl.operations.ModifyOperation Exception during response processing.
org.apache.sling.api.resource.PersistenceException: Unable to create node at /etc/acs-commons/manage-controlled-processes
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.create(JcrResourceProvider.java:480) [org.apache.sling.jcr.resource:3.0.18]
	at org.apache.sling.resourceresolver.impl.providers.stateful.AuthenticatedResourceProvider.create(AuthenticatedResourceProvider.java:182) [org.apache.sling.resourceresolver:1.6.8]
	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.create(ResourceResolverControl.java:379) [org.apache.sling.resourceresolver:1.6.8]
	at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.create(ResourceResolverImpl.java:971) [org.apache.sling.resourceresolver:1.6.8]
	at org.apache.sling.servlets.post.impl.operations.AbstractCreateOperation.deepGetOrCreateResource(AbstractCreateOperation.java:598) [org.apache.sling.servlets.post:2.3.26]
	at org.apache.sling.servlets.post.impl.operations.AbstractCreateOperation.processCreate(AbstractCreateOperation.java:146) [org.apache.sling.servlets.post:2.3.26]
	at org.apache.sling.servlets.post.impl.operations.ModifyOperation.doRun(ModifyOperation.java:83) [org.apache.sling.servlets.post:2.3.26]
`

This should hit a servlet registered by resource type, but the page doesn't exist, resulting in a constraint violation while trying to create the node.  It looks like the page was moved to /apps, but the form post location was never updated to match.

**Comment by badvision** [comment]
Looks like the javascript client library was pointing to the old /etc location and wasn't updated when we moved the page to /apps/acs-commons.  Fixing now.

**Comment by badvision** [comment]
Thanks @shsteimer!  I posted a fix to the master branch.
