### ISSUE TITLE
MCP Data Importer null pointer exception at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)

### ISSUE THREAD

**Issue by JasonUSC** [Adobe-Consulting-Services/acs-aem-commons#2176]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5 sp3
* [ ] ACS AEM Commons Version: 4.4.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

Data importer should be able to execute without null pointer exceptions.

### Actual Behavior

Data Importer fails with a null pointer exception on some xlsx files. It is unclear why some work and some do not.

Error starting managed process Data Importer: No description
com.adobe.acs.commons.mcp.impl.ProcessInstanceImpl
Stack Trace
java.lang.NullPointerException: null
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
at com.adobe.acs.commons.data.Spreadsheet.buildSpreadsheet(Spreadsheet.java:161)
at com.adobe.acs.commons.data.Spreadsheet.buildSpreadsheet(Spreadsheet.java:137)
at com.adobe.acs.commons.mcp.impl.processes.DataImporter.buildProcess(DataImporter.java:201)
at com.adobe.acs.commons.mcp.impl.ProcessInstanceImpl.run(ProcessInstanceImpl.java:199)
at com.adobe.acs.commons.mcp.impl.ControlledProcessManagerServlet.doStartProcess(ControlledProcessManagerServlet.java:152)
at com.adobe.acs.commons.mcp.impl.ControlledProcessManagerServlet.doGet(ControlledProcessManagerServlet.java:97)
at com.adobe.acs.commons.mcp.impl.ControlledProcessManagerServlet.doPost(ControlledProcessManagerServlet.java:84)

### Steps to Reproduce
1. vanilla install of 6.5 sp3 on local machine with the latest ACS aem commons package
2. try to upload an excel file -- some work, some fail with null description

**Comment by JasonUSC** [comment]
I'm thinking maybe the array list delimiter ":" is being incorrectly applied to the "path" column.
