### ISSUE TITLE
URL Asset Import - files not uploading using path prefix field

### ISSUE THREAD

**Issue by ni3gitrepo** [Adobe-Consulting-Services/acs-aem-commons#2348]
## Required Information

AEM 6.5.4 ( Service Pack 4)
ACS AEM Commons version (4.5, 4.5.2,4.6)
Reproducible on Latest? yes

### Expected Behavior

Not able to import assets using URL prefix in the given form. 

If I am setting up default Prefix  as “file:///C:/Pictures/dam/Biking” and source in the file(xlsx) as “cycling_5.jpg” 
getting below error - 
java.net.MalformedURLException: no protocol: group-mountain-bikers.jpg
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at com.adobe.acs.commons.mcp.impl.processes.asset.FileOrRendition$UrlConnectionSource.getConnection(FileOrRendition.java:188)
	at com.adobe.acs.commons.mcp.impl.processes.asset.FileOrRendition$UrlConnectionSource.getLength(FileOrRendition.java:208)
	at com.adobe.acs.commons.mcp.impl.processes.asset.AssetIngestor.canImportFile(AssetIngestor.java:454)
	at com.adobe.acs.commons.mcp.impl.processes.asset.UrlAssetImport.lambda$importAssets$10(UrlAssetImport.java:242)
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:200)
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.runActionAndLogErrors(ActionManagerImpl.java:167)
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.lambda$deferredWithResolver$0(ActionManagerImpl.java:159)
	at com.adobe.acs.commons.fam.impl.TimedRunnable.run(TimedRunnable.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

### Actual Behavior

Assets should get imported into given target path without any error.  

### Steps to Reproduce

1. install AEM 6.5.4
2. install latest ACS AEM Commons package (4.7)
3. invoke mcp tool using http://localhost:4502/apps/acs-commons/content/manage-controlled-processes.html 
4. invoke url asset import 
5. use default prefix as "file:///C:/Pictures/dam/Biking"
6. copy some assets in "c:/Pictures/dam/Biking" path
7. enter the same assets name in source column in sample.xlsx (please find attached)
8. Submit the form

### Links

https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp-tools/asset-ingestion/url-asset-ingestor/index.html

[sample-url-asset-import.xlsx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/4832723/sample-url-asset-import.xlsx)

**Comment by ni3gitrepo** [comment]
Able to fix this issue after making below changes in given parameter - 
Prefix path - “file:///C:/Pictures/dam/Biking/” 
Source (in xlsx) “/cycling_5.jpg”
