### ISSUE TITLE
Asset Ingestor gives error when using SFTP URL as source on Local AEM setup

### ISSUE THREAD

**Issue by pmohapatra-publicissapient** [Adobe-Consulting-Services/acs-aem-commons#2412]
## Required Information

Local Configuration Details:
- AEM 6.5 with Service Pack 6.5.6 and S3 integration
- ACS AEM Commons Version 4.8.0
- Local Test SFTP setup with Rebex Tiny SFTP Server, which is accessible over SFTP clients
- Reproducible on Latest? yes (same behavior on ACS AEM Commons Version 4.8.4)

### Expected Behavior

When I provide SFTP URL as the source in Asset Ingestor form and start the process, I expect the assets in the SFTP source to be imported into AEM DAM target folder.

### Actual Behavior

Instead, the process shows the loader indefinitely and I observe the following in error.log:

21.09.2020 10:29:00.888 *ERROR* [0:0:0:0:0:0:0:1 [1600664340821] POST /apps/acs-commons/content/manage-controlled-processes/jcr:content.start.json HTTP/1.1] com.day.cq.wcm.core.impl.WCMDebugFilter Error during include of SlingRequestPathInfo: path='/apps/acs-commons/content/manage-controlled-processes/jcr:content', selectorString='start', extension='json', suffix='null'
java.lang.NoClassDefFoundError: javax/crypto/spec/SecretKeySpec
	at acscommons.com.jcraft.jsch.jce.AES256CTR.init(AES256CTR.java:55) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at acscommons.com.jcraft.jsch.Session.checkCipher(Session.java:2497) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at acscommons.com.jcraft.jsch.Session.checkCiphers(Session.java:2474) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at acscommons.com.jcraft.jsch.Session.send_kexinit(Session.java:624) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at acscommons.com.jcraft.jsch.Session.connect(Session.java:307) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at acscommons.com.jcraft.jsch.Session.connect(Session.java:183) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at com.adobe.acs.commons.mcp.impl.processes.asset.FileAssetIngestor$SftpHierarchicalElement.openChannel(FileAssetIngestor.java:343) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at com.adobe.acs.commons.mcp.impl.processes.asset.FileAssetIngestor$SftpHierarchicalElement.retrieveDetails(FileAssetIngestor.java:367) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at com.adobe.acs.commons.mcp.impl.processes.asset.FileAssetIngestor$SftpHierarchicalElement.access$000(FileAssetIngestor.java:299) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at com.adobe.acs.commons.mcp.impl.processes.asset.FileAssetIngestor.getBaseFolder(FileAssetIngestor.java:117) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at com.adobe.acs.commons.mcp.impl.processes.asset.FileAssetIngestor.buildProcess(FileAssetIngestor.java:104) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at com.adobe.acs.commons.mcp.impl.ProcessInstanceImpl.run(ProcessInstanceImpl.java:198) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at com.adobe.acs.commons.mcp.impl.ControlledProcessManagerServlet.doStartProcess(ControlledProcessManagerServlet.java:152) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at com.adobe.acs.commons.mcp.impl.ControlledProcessManagerServlet.doGet(ControlledProcessManagerServlet.java:97) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]
	at com.adobe.acs.commons.mcp.impl.ControlledProcessManagerServlet.doPost(ControlledProcessManagerServlet.java:84) [com.adobe.acs.acs-aem-commons-bundle:4.8.0]

### Steps to Reproduce

1. Installed AEM 6.5 with latest Service Pack (6.5.6).
2. Configured to use AWS S3 as data store.
3. Installed ACS AEM Commons 4.8.0
4. Setup test SFTP on local using Rebex Tiny SFTP Server
5. Tested that the SFTP server is accessible from SFTP client (WinSCP)
6. Selected Asset Ingestor process in Managed Controlled Processes
7. Entered appropriate values in form and provided SFTP folder path in 'Source'.
8. Started the process.

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by badvision** [comment]
Are you sure that you're not having DNS lookup issues?  I used SFTP locally when I wrote this tool and I cannot say I was having this kind of issue.

**Comment by SridharDhurjeti** [comment]
Hi

I got the same issue, do we need to do anything to fix this issue.

I tried in AEM 6.5 with ACS AEM Commons 5.0.12.
We setup test SFTP server on another machine, and tried  to access the files in different machine from "Asset Ingestor" with SFTP url (sftp://<<ipaddress of remote machine>> then I got the same issue in AEM error.log. But when I tried same SFTP URL with FileZilla, I could able to access the files.

Can you pls. let me know how we can access files through SFTP from Asset Ingestor?

Thanks
Sri

**Comment by jdecker123** [comment]
I am having the same issue ..
...
Caused by: java.lang.ClassNotFoundException: javax.crypto.spec.SecretKeySpec not found by com.adobe.acs.acs-aem-commons-bundle [592]
at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1597)
at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
...

**Comment by badvision** [comment]
What version of Java are you using?  Oracle JDK, OpenJDK, Azul, etc?

Depending on what you have installed you might not have the needed jce.jar in your sdk's lib folder.

For example:
https://www.oracle.com/java/technologies/java-archive-downloads-java-plat-downloads.html#JCE-1_2_2-G-JS

This is a likely solution but without knowing more about your environment I can't really say with 100% certainty.

**Comment by rajakumare1** [comment]
We are using the Oracle JDK

**Comment by jdecker123** [comment]
Hello,

This issue is not resolved. 
We are using Java 11.0.12 2021-07-20 LTS
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

According to Oracle, we do not need policy files see  
https://www.oracle.com/java/technologies/javase-jce-all-downloads.html

Current versions of the JDK do not require these policy files. They are provided here for use with older version of the JDK.
 JDK 9 and later offer the stronger cryptographic algorithms by default.
 The unlimited policy files are required only for JDK 8, 7, and 6 updates earlier than 8u161, 7u171, and 6u181. On those versions and later, the stronger cryptographic algorithms are available by default.
