### ISSUE TITLE
S3 Asset Ingestor gives UnknownHostException error

### ISSUE THREAD

**Issue by PrateekMohapatra** [Adobe-Consulting-Services/acs-aem-commons#2417]
## Required Information

Local Configuration Details:

- AEM 6.5 with Service Pack 6.5.6 and S3 integration (connector version 1.10.10)
- ACS AEM Commons Version 4.8.4
- Reproducible on Latest? yes

### Expected Behavior

When I provide Bucket Name, Access and Secret Key, and Endpoint URL details in S3 Asset Ingestor form and start the process, I expect the assets in the S3 source to be imported into AEM DAM target folder.

### Actual Behavior

Instead, the process fails and I observe the following in error.log:

23.09.2020 10:56:29.524 *ERROR* [pool-71-thread-4] com.adobe.acs.commons.fam.impl.ActionManagerImpl Error in action S3 Asset Ingestor: https://s3.console.aws.amazon.com/s3/buckets/{bucketName}->/content/dam/aws/s3: Create Folders (2e7520bc-dd30-4ea8-b80a-3ea9022a6ff2)
com.amazonaws.SdkClientException: Unable to execute HTTP request: {bucketName}.s3.console.aws.amazon.com
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1189) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1135) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:752) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5052) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4998) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4992) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:895) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:869) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.adobe.acs.commons.mcp.impl.processes.asset.S3AssetIngestor.lambda$createFolders$0(S3AssetIngestor.java:121)
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:200)
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.runActionAndLogErrors(ActionManagerImpl.java:167)
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.lambda$deferredWithResolver$0(ActionManagerImpl.java:159)
	at com.adobe.acs.commons.fam.impl.TimedRunnable.run(TimedRunnable.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
**Caused by: java.net.UnknownHostException: {bucketName}.s3.console.aws.amazon.com**
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) [org.apache.httpcomponents.httpclient:4.5.4]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) [org.apache.httpcomponents.httpclient:4.5.4]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.http.conn.$Proxy17.connect(Unknown Source) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) [org.apache.httpcomponents.httpclient:4.5.4]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) [org.apache.httpcomponents.httpclient:4.5.4]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) [org.apache.httpcomponents.httpclient:4.5.4]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) [org.apache.httpcomponents.httpclient:4.5.4]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) [org.apache.httpcomponents.httpclient:4.5.4]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) [org.apache.httpcomponents.httpclient:4.5.4]
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1311) [com.amazonaws.aws-java-sdk-osgi:1.11.700]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127) [com.amazonaws.aws-java-sdk-osgi:1.11.700]

### Steps to Reproduce

1. Installed AEM 6.5 with latest Service Pack (6.5.6).
2. Configured to use AWS S3 (using latest connector 1.10.10) as data store.
3. Setup another bucket for import of assets and granted the user all permissions.
4. Tested that the SFTP server is accessible from SFTP client (WinSCP)
5. Selected S3 Asset Ingestor process in Managed Controlled Processes
6. Entered appropriate values in form and provided Bucket Name, Access Key, Secret Key, and Endpoint URL.
7. Started the process.

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by joerghoh** [comment]
UnknownHostNameException indicates that the DNS name cannot get resolved. I see 2 ways how this can happen:

* The system where this code is running is using a DNS server, which cannot resolve that hostname. This often happens in locked-down environments, where for security reasons the DNS is not able to resolve external names.
* You have a typo in the hostname.

**Comment by kwin** [comment]
Seems that `{bucketName}` is not properly resolved inside the URL `{bucketName}.s3.console.aws.amazon.com`. Maybe wrong parametrisation?

**Comment by PrateekMohapatra** [comment]
@kwin I just masked the name in the logs that I provided here to generalize the fact that I had tried a couple of buckets and it didn't work with either. It does log the correct bucket name being tried to be accessed. Hope this clarifies.

@joerghoh Thanks for your inputs. Please find my comments below:
- I ran the utility on my local AEM instance as preparation before we setup the client servers. Is there any additional setting/configuration that would need to be done either on AEM or on AWS S3 console for access on local?
- I have validated for any typo and there is none.

Considerations:
1. I have setup my local AEM with S3 datastore and that works without any issues, i.e. upload is happening from AEM -> S3 
2. I could write code using AWS SDK to access the same bucket with the same set of access and secret keys, and also could read the assets available in the bucket. If I could make the ACS utility work, it would save the coding overhead for the entire import activity.

**Comment by joerghoh** [comment]
@PrateekMohapatra so you mean, that any other access to that bucket from your development machine (localhost) to S3 is working fine? Ok, that would rule networking/routing issues.

But potentially the hostname pattern has changed in the past and a new pattern is now used. At least https://docs.aws.amazon.com/en_en/AmazonS3/latest/dev/VirtualHosting.html suggests a different pattern.

Can you try the PR at https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2426 ? I updated the aws SDK to the latest version, maybe that already does the trick.

**Comment by justinedelson** [comment]
It seems unlike that the version used at build time would be related -- this is a runtime issue.
