### ISSUE TITLE
PagesReferenceProvider and NPE

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#246]
Logged for my good friend Srini...

AME6 -  On activation of PagesReferenceProvider I got the error like this..

01.07.2014 17:37:48.427 _WARN_ [0:0:0:0:0:0:0:1 [1404250668405] GET /libs/wcm/core/content/reference.json HTTP/1.1] com.day.cq.wcm.webservicesupport.impl.ConfigurationManagerImpl Exception while searching for cloudservice resource
java.lang.NullPointerException: null
at com.day.cq.wcm.webservicesupport.impl.ConfigurationManagerImpl.getConfigurationResource(ConfigurationManagerImpl.java:311)
at com.day.cq.wcm.webservicesupport.impl.ConfigurationManagerImpl.getConfigurations(ConfigurationManagerImpl.java:271)
at com.day.cq.wcm.webservicesupport.impl.ConfigurationReferenceProvider.findReferences(ConfigurationReferenceProvider.java:47)
…  
…
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
        at com.day.cq.wcm.core.impl.reference.ActivationReferenceSearchServlet.doGet(ActivationReferenceSearchServlet.java:130)
        ... 126 common frames omitted

**Comment by brennhill** [comment]
@davidjgonzalez  I am now seeing this on our project.  Can you tell me where to disable this configurationReferenceProvider to resolve the issue?

**Comment by davidjgonzalez** [comment]
Closing as has not been reported for some time.

**Comment by sachin-arora** [comment]
@davidjgonzalez : I am facing the same issue with acs-aem-commons-content-2.3.0.zip package.

**Comment by davidjgonzalez** [comment]
What version of AEM are you on (and are they're any SPs or HFs of note that are added?)

**Comment by sachin-arora** [comment]
@davidjgonzalez : I am using AEM 6.1 with SP2. This error does not come in preview mode.
