### ISSUE TITLE
ACS Commons fails in cloud

### ISSUE THREAD

**Issue by vbrk1971** [Adobe-Consulting-Services/acs-aem-commons#2647]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______AEM cloud 
* [ ] ACS AEM Commons Version: 5.0.4
* [ ] Reproducible on Latest? yes

### Expected Behavior
When ACS Commons bundle is deployed, I should be able to create generic lists

### Actual Behavior

Tried with AEM SDK 3.5 version and it worked fine locally. Tried with SDK 6.5 and got scriptvalidationerror.  When pushed the code the cloud through CM, and tried to access List, it redirects to AEM banner with unexpected error message
![image](https://user-images.githubusercontent.com/87533987/125959718-20ce23ab-3111-4ac5-b104-76d1d58dd692.png)

### Steps to Reproduce

Install ACS COmmons on project and deploy

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by davidjgonzalez** [comment]
What do the  AEM error logs say?

**Comment by vbrk1971** [comment]
16.07.2021 13:51:37.663 [cm-p35622-e147206-aem-author-59cf95d46f-lggxl] *ERROR* [205.144.62.1 [1626443497623] GET /mnt/overlay/acs-commons/components/utilities/genericlist.html HTTP/1.1] libs.granite.ui.components.shell.propertiespage Unable to render properties page correctly
javax.servlet.jsp.JspTagException: org.apache.sling.api.scripting.ScriptEvaluationException: 
	at org.apache.sling.scripting.jsp.taglib.AbstractDispatcherTagHandler.doEndTag(AbstractDispatcherTagHandler.java:138) [org.apache.sling.scripting.jsp.taglib:2.4.0]
	at libs.granite.ui.components.shell.propertiespage.propertiespage__002e__jsp._jspService(propertiespage__002e__jsp.java:869) [aem-precompiled-scripts:6.6.0.V24016]
	at org.apache.sling.scripting.jsp.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [org.apache.sling.scripting.jsp:2.5.2]
	at org.apache.sling.scripting.jsp.PrecompiledJSPRunner.callPrecompiledJSP(PrecompiledJSPRunner.java:72) [org.apache.sling.scripting.jsp:2.5.2]
	at org.apache.sling.scripting.jsp.JspScriptEngineFactory$JspScriptEngine.eval(JspScriptEngineFactory.java:583) [org.apache.sling.scripting.jsp:2.5.2]
	at org.apache.sling.scripting.core.impl.bundled.PrecompiledScript.eval(PrecompiledScript.java:54) [org.apache.sling.scripting.core:2.3.6]
	at org.apache.sling.scripting.core.impl.bundled.ScriptContextProvider$ExecutableContext.eval(ScriptContextProvider.java:135) [org.apache.sling.scripting.core:2.3.6]
	at org.apache.sling.scripting.core.impl.bundled.AbstractBundledRenderUnit.eval(AbstractBundledRenderUnit.java:190) [org.apache.sling.scripting.core:2.3.6]
	at org.apache.sling.servlets.resolver.internal.bundle.BundledScriptServlet.service(BundledScriptServlet.java:78) [org.apache.sling.servlets.resolver:2.7.14]
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:574) [org.apache.sling.engine:2.7.6]
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:45) [org.apache.sling.engine:2.7.6]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:88) [org.apache.sling.engine:2.7.6]
	at com.day.cq.wcm.core.impl.WCMDeveloperModeFilter.doFilter(WCMDeveloperModeFilter.java:119) [com.day.cq.wcm.cq-wcm-core:5.13.214]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78) [org.apache.sling.engine:2.7.6]
	at com.day.cq.wcm.core.impl.WCMDebugFilter.doFilter(WCMDebugFilter.java:138) [com.day.cq.wcm.cq-wcm-core:5.13.214]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78) [org.apache.sling.engine:2.7.6]
	at com.adobe.acs.commons.granite.ui.components.impl.include.IncludeDecoratorFilterImpl.doFilter(IncludeDecoratorFilterImpl.java:92) [com.adobe.acs.acs-aem-commons-bundle:5.0.4]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78) [org.apache.sling.engine:2.7.6]
	at com.adobe.granite.uriprovider.dba.DBAHeaderFilter.doFilter(DBAHeaderFilter.java:107) [com.adobe.granite.uriprovider.dba:0.2.6]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78) [org.apache.sling.engine:2.7.6]
	at com.adobe.granite.metrics.knownerrors.impl.ErrorLoggingComponentFilter.doFilter(ErrorLoggingComponentFilter.java:76) [com.adobe.granite.metrics.knownerrors:0.0.14]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78) [org.apache.sling.engine:2.7.6]
	at com.day.cq.wcm.core.impl.monitoring.PageComponentRequestFilter.doFilter(PageComponentRequestFilter.java:105) [com.day.cq.wcm.cq-wcm-core:5.13.214]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78) [org.apache.sling.engine:2.7.6]
	at com.day.cq.wcm.core.impl.WCMComponentFilter.filterRootInclude(WCMComponentFilter.java:375) [com.day.cq.wcm.cq-wcm-core:5.13.214]
	at com.day.cq.wcm.core.impl.WCMComponentFilter.doFilter(WCMComponentFilter.java:190) [com.day.cq.wcm.cq-wcm-core:5.13.214]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78) [org.apache.sling.engine:2.7.6]
	at com.day.cq.wcm.core.impl.page.PageLockFilter.doFilter(PageLockFilter.java:91) [com.day.cq.wcm.cq-wcm-core:5.13.214]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78) [org.apache.sling.engine:2.7.6]
[author_aemerror_2021-07-16.log](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/6831265/author_aemerror_2021-07-16.log)

**Comment by vbrk1971** [comment]
I am getting same error when installing locally on and SDK Version higher than 3.5 - same project

**Comment by davidjgonzalez** [comment]
Just checked, and this should be fixed in latest AEM CS (AEM SDK and real AEM CS).

What version of AEM SDK/CS are you on (the version should look like a date/time stamp .. something like: `2021.6.5540.20210615T210737Z-210527`

Im not sure what AEM SDK 3.5 or 6.5 means

**Comment by vbrk1971** [comment]
Our cloud is using 2021.6.5540.20210615T210737Z. Not sure if that is the latest version and if not, when it will be updated.

**Comment by davidjgonzalez** [comment]
Latest AEM SDK version is:  `v2021.7.5607.20210705T063041Z-210600`

can you try that?

**Comment by davidjgonzalez** [comment]
If you can figure out why this build's Unit test fails [1] running in Github Actions, we can merge a fix on our side too (though with the product fix this shouldn't be necessary). Oddly the unit test is fine when run locally.

[1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2618

**Comment by vbrk1971** [comment]
I can try latest sdk  on my local. But won't be able to deploy to cloud dev
until they upgrade the release. Not sure why pros and stage use later
version than dev

**Comment by davidjgonzalez** [comment]
AEM CS Production and Stage are always up to date, Dev requires a "manual" update. Just how it works.
