### ISSUE TITLE
Redirect Manager Null Pointer

### ISSUE THREAD

**Issue by hoosierPadre** [Adobe-Consulting-Services/acs-aem-commons#2673]
## Required Information

* [ ] AEM Version - 2021.8.5743.20210817T230726Z (ACS)
* [ ] ACS AEM Commons Version: 5.06
* [ ] Reproducible on Latest? yes

### Expected Behavior

When editing redirects in the redirect manager changes should be saved and then executed via the com.adobe.acs.commons.redirects.filter.RedirectFilter when called at the page level

### Actual Behavior 

When editing redirects in the redirect manager changes are not being saved (NPE are being thrown). Consequently redirects aren't executed when accessing paths listed at the page level filter.

20.08.2021 15:13:47.778 *WARN* [sling-oak-observation-10] org.apache.jackrabbit.oak.jcr.observation.ChangeProcessor Error while dispatching observation events for //*[11111b]@org.apache.sling.jcr.resource.internal.JcrResourceListener
java.lang.NullPointerException: null
	at com.adobe.acs.commons.redirects.filter.RedirectFilter.onChange(RedirectFilter.java:273) [com.adobe.acs.acs-aem-commons-bundle:5.0.6]
	at org.apache.sling.resourceresolver.impl.observation.BasicObservationReporter.reportChanges(BasicObservationReporter.java:211) [org.apache.sling.resourceresolver:1.7.2]
	at org.apache.sling.jcr.resource.internal.JcrResourceListener.onEvent(JcrResourceListener.java:155) [org.apache.sling.jcr.resource:3.0.22]
	at org.apache.jackrabbit.commons.observation.ListenerTracker$1.onEvent(ListenerTracker.java:190) [org.apache.jackrabbit.jackrabbit-jcr-commons:2.20.0]
	at org.apache.jackrabbit.oak.jcr.observation.ChangeProcessor.contentChanged(ChangeProcessor.java:513) [org.apache.jackrabbit.oak-jcr:1.39.0.R1887543]
	at org.apache.jackrabbit.oak.plugins.observation.FilteringDispatcher.contentChanged(FilteringDispatcher.java:52) [org.apache.jackrabbit.oak-core:1.39.0.R1887543]
	at org.apache.jackrabbit.oak.spi.commit.BackgroundObserver$1$1.call(BackgroundObserver.java:127) [org.apache.jackrabbit.oak-store-spi:1.39.0.R1887543]
	at org.apache.jackrabbit.oak.spi.commit.BackgroundObserver$1$1.call(BackgroundObserver.java:121) [org.apache.jackrabbit.oak-store-spi:1.39.0.R1887543]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

### Steps to Reproduce

We haven't yet tested installing this on a vanilla AEM project but is occurring when embedding AEM Commons into our project codebase. As far as we've been able to determine to date this feature doesn't appear to be completely compatible with the latest AEM as claimed.

Display appears to also have issues on this version of AEM

![Screen Shot 2021-08-20 at 3 02 46 PM](https://user-images.githubusercontent.com/89278517/130293685-2551e4c7-4765-4cfa-8f37-f1354e0eeb28.png)

**Comment by YegorKozlov** [comment]
Did you enable RedirectFilter in the osgi configuration?

**Comment by hoosierPadre** [comment]
@YegorKozlov - I think I've identified the issue.

There appears to be a typo in the documentation and also the snippet you have above

enabed should actually be enabled

As you stated when this value is set the NPE is removed.

We're currently testing but this was something we missed after reviewing it repeatedly also so thanks for the pointer.

**Comment by YegorKozlov** [comment]
The typo is a good catch. There are two PRs related to this ticket:
1. correct typos in the documentation:https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/pull/218
2. change the code to avoid NPE if the "enabled" flag not set: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2673 The flag should not prevent users from editing redirect rules.

both will be included in next release.
