### ISSUE TITLE
NamedImageTransformer provided with incorrect parameters

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#2709]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: CloudService
* [X] ACS AEM Commons Version: 4.11
* [ ] Reproducible on Latest? yes/no

### Expected Behavior

stacktraces should not happen:

### Actual Behavior
We see this stacktrace:

[92.184.117.250 [1633015494300] GET /content/dam/path/to/some/asset.jpg.transform/650/image.jpg HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.IndexOutOfBoundsException: off < 0 || len < 0 || off + len > b.length!
	at java.desktop/javax.imageio.stream.ImageInputStreamImpl.readFully(Unknown Source)
	at java.desktop/com.sun.imageio.plugins.tiff.TIFFIFD.readFieldValue(Unknown Source)
	at java.desktop/com.sun.imageio.plugins.tiff.TIFFIFD.initialize(Unknown Source)
	at java.desktop/com.sun.imageio.plugins.tiff.TIFFImageMetadata.initializeFromStream(Unknown Source)
	at java.desktop/com.sun.imageio.plugins.tiff.TIFFImageReader.readMetadata(Unknown Source)
	at java.desktop/com.sun.imageio.plugins.tiff.TIFFImageReader.seekToImage(Unknown Source)
	at java.desktop/com.sun.imageio.plugins.tiff.TIFFImageReader.prepareRead(Unknown Source)
	at java.desktop/com.sun.imageio.plugins.tiff.TIFFImageReader.read(Unknown Source)
	at com.day.image.Layer.<init>(Layer.java:706)
	at com.day.image.Layer.<init>(Layer.java:599)
	at com.day.image.Layer.<init>(Layer.java:522)
	at com.day.cq.commons.ImageHelper.createLayer(ImageHelper.java:173)
	at com.day.cq.commons.ImageResource.getLayer(ImageResource.java:633)
	at com.adobe.acs.commons.images.impl.NamedTransformImageServlet.getLayer(NamedTransformImageServlet.java:446)
	at com.adobe.acs.commons.images.impl.NamedTransformImageServlet.doGet(NamedTransformImageServlet.java:217)

(It's totally clear to me that renditions should be created/handled on AEM CS differently, but I think that this issue ist most likely to appear on AEM 6.x as well.)

**Comment by davidjgonzalez** [comment]
@joerghoh whats the cause of this exactly? 

Is the request here is to capture this exception and throw the appropriate servlet exception w/ status?
