### ISSUE TITLE
IN place upgrade. Generic list issue breaking

### ISSUE THREAD

**Issue by manojBabuDev** [Adobe-Consulting-Services/acs-aem-commons#2765]
* AEM Version 6.5
* including Service Packs6.5.10
* ACS AEM Commons Version:5.0.10
* Reproducible on Latest? yes

We are currently upgrading aem 6.4 to 6.5. We notice the generic list is not loading on classic and touch UI?

Caused by: org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper$1: java.lang.NullPointerException
at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.handleJspExceptionInternal(JspServletWrapper.java:655) [org.apache.sling.scripting.jsp:2.3.6]
at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:608) [org.apache.sling.scripting.jsp:2.3.6]
at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:533) [org.apache.sling.scripting.jsp:2.3.6]
at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:449) [org.apache.sling.scripting.jsp:2.3.6]
at org.apache.sling.scripting.jsp.JspScriptEngineFactory.callJsp(JspScriptEngineFactory.java:339) [org.apache.sling.scripting.jsp:2.3.6]
at org.apache.sling.scripting.jsp.JspScriptEngineFactory.access$100(JspScriptEngineFactory.java:97) [org.apache.sling.scripting.jsp:2.3.6]
at org.apache.sling.scripting.jsp.JspScriptEngineFactory$JspScriptEngine.eval(JspScriptEngineFactory.java:600) [org.apache.sling.scripting.jsp:2.3.6]
at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:388) [org.apache.sling.scripting.core:2.3.2]
at org.apache.sling.scripting.core.impl.DefaultSlingScript.eval(DefaultSlingScript.java:184) [org.apache.sling.scripting.core:2.3.2]
at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:491) [org.apache.sling.scripting.core:2.3.2]
at com.adobe.granite.ui.components.impl.BaseComponentHelper.call(BaseComponentHelper.java:568) [com.adobe.granite.ui.commons:5.10.15.CQ650-B0004]
at com.adobe.granite.ui.components.ComponentHelper.call(ComponentHelper.java:758) [com.adobe.granite.ui.commons:5.10.15.CQ650-B0004]
at org.apache.jsp.libs.granite.ui.components.coral.foundation.form.field.field_jsp._jspService(field_jsp.java:300)
at org.apache.sling.scripting.jsp.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [org.apache.sling.scripting.jsp:2.3.6]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [org.apache.felix.http.servlet-api:1.1.2]
at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:502) [org.apache.sling.scripting.jsp:2.3.6]
... 355 common frames omitted
Caused by: java.lang.NullPointerException: null
22.12.2021 15:37:23.958 *ERROR* [10.43.0.12 [1640187443519] GET /mnt/overlay/acs-commons/components/utilities/genericlist.html HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught SlingException
java.lang.NullPointerException: null

**Comment by SachinMali** [comment]
@manojBabuDev Please see if this is fixed with the latest 5.2.0 version..
