### ISSUE TITLE
ACS Common Generic List - Throwing exception if am trying to add more than 10 items

### ISSUE THREAD

**Issue by sambasivaraj** [Adobe-Consulting-Services/acs-aem-commons#2783]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: **AEM Cloud Version 2022.1.6228.20220123T154100Z**
* [ ] ACS AEM Commons Version: **5.1.2**
* [ ] Reproducible on Latest? **YES**

### Expected Behavior

I should be able to add as many items using the Generic list ACS Common feature

### Actual Behavior

If am trying to add more than 10 items to generic list , am getting the exception as below 
`aused by: org.apache.sling.api.SlingException: javax.servlet.ServletException: javax.servlet.jsp.JspTagException: org.apache.sling.api.request.TooManyCallsException: BundledScriptServlet (/libs/granite/ui/components/coral/foundation/form/field/field.jsp)
	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.handleJspExceptionInternal(JspServletWrapper.java:685) [org.apache.sling.scripting.jsp:2.5.2]
	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:602) [org.apache.sling.scripting.jsp:2.5.2]
	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:519) [org.apache.sling.scripting.jsp:2.5.2]
	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:445) [org.apache.sling.scripting.jsp:2.5.2]
	at org.apache.sling.scripting.jsp.JspScriptEngineFactory$JspScriptEngine.callJsp(JspScriptEngineFactory.java:501) [org.apache.sling.scripting.jsp:2.5.2]
	at org.apache.sling.scripting.jsp.JspScriptEngineFactory$JspScriptEngine.eval(JspScriptEngineFactory.java:586) [org.apache.sling.scripting.jsp:2.5.2]
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:388) [org.apache.sling.scripting.core:2.3.6]`

### Steps to Reproduce

Create a  latest Local AEM SDK version 
Deploy ACC Common 5.1.2 version
Navigate to http://localhost:4502/generic-lists.html/etc/acs-commons/lists
Create a generic list 
Add more than 10 items in the list and observe the behaviour 
User will see too many call exception in the error log and you will be able to view all the items in Generic list UI

**Comment by hearora** [comment]
did u try updating the number of calls per per request in apache Sling man servlet configuration ? Hope this helps
![image](https://user-images.githubusercontent.com/50401632/156567167-c7deb25f-020b-4092-a6ed-bea6c1cefb38.png)

**Comment by SachinMali** [comment]
Apart from above option to BUMP the 'Number Of calls Per Request', the latest ACS Commons release 5.2.0 might help to resolve it. Please check...

**Comment by adamcin** [comment]
@SachinMali I believe the 5.2.0 solution depends on generic list localization being disabled. It doesn't fix the situation if localization is desired.

**Comment by davidjgonzalez** [comment]
I think @adamcin suggestion might be best -- otherwise I think a rewrite that simplifies the impl could be a reasonable option. (maybe something more akin to how it was originally designed - just not sure about back compat to the current version)
