### ISSUE TITLE
Renovator fails to move asset folder if folder has a review task

### ISSUE THREAD

**Issue by josephrignanese** [Adobe-Consulting-Services/acs-aem-commons#2832]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.12, 6.5.5 (probably other versions also)
* [x] ACS AEM Commons Version: 5.3.0
* [x] Reproducible on Latest? yes

### Expected Behavior

Renovator MCP process should move folders as described in the documentation https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp-tools/renovator/index.html

### Actual Behavior

The process fails partway through the move (in the buildStructures step), leaving a partially completed move committed.

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

1. Start from a vanilla AEM 6.5.12 instance
2. Go to Assets area and create a review task on a folder (e.g. /content/dam/we-retail/en/activities/hiking)

![Screen Shot 2022-04-29 - 1 - review-task](https://user-images.githubusercontent.com/17347917/165902664-b246a390-0609-4c29-82ea-72ee4352cecb.png)
![Screen Shot 2022-04-29 - 2 - review-task](https://user-images.githubusercontent.com/17347917/165902681-7ed44a16-2caf-44f7-ac10-b252956c36cc.png)

3. Trigger the MCP renovator process to move the folder (do not select "Dry run")
4. Observe the process fails with error
5. Observe the process has made some commits (e.g. target folders created), so the move is part way in progress

Example stack trace
```
29.04.2022 17:15:35.511 *ERROR* [pool-33-thread-3] com.adobe.acs.commons.fam.impl.ActionManagerImpl Error in action Renovator: Publish mode none: Build destination (0d1e996d-6df0-4f83-9fcc-b11cb0496777)
org.apache.sling.api.resource.PersistenceException: Unable to delete resource
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.delete(JcrResourceProvider.java:500) [org.apache.sling.jcr.resource:3.0.18]
	at org.apache.sling.resourceresolver.impl.providers.stateful.AuthenticatedResourceProvider.delete(AuthenticatedResourceProvider.java:193) [org.apache.sling.resourceresolver:1.7.10]
	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.delete(ResourceResolverControl.java:413) [org.apache.sling.resourceresolver:1.7.10]
	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.copy(ResourceResolverControl.java:606) [org.apache.sling.resourceresolver:1.7.10]
	at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.copy(ResourceResolverImpl.java:1126) [org.apache.sling.resourceresolver:1.7.10]
	at com.adobe.acs.commons.mcp.impl.processes.renovator.MovingFolder.lambda$move$0(MovingFolder.java:79) [com.adobe.acs.acs-aem-commons-bundle:5.3.0]
	at com.adobe.acs.commons.fam.actions.Actions.lambda$retry$2(Actions.java:141) [com.adobe.acs.acs-aem-commons-bundle:5.3.0]
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:200) [com.adobe.acs.acs-aem-commons-bundle:5.3.0]
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.runActionAndLogErrors(ActionManagerImpl.java:167) [com.adobe.acs.acs-aem-commons-bundle:5.3.0]
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.lambda$deferredWithResolver$0(ActionManagerImpl.java:159) [com.adobe.acs.acs-aem-commons-bundle:5.3.0]
	at com.adobe.acs.commons.fam.impl.TimedRunnable.run(TimedRunnable.java:91) [com.adobe.acs.acs-aem-commons-bundle:5.3.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.jcr.InvalidItemStateException: This item [/content/dam/we-retail/en/activities/hiking-moved/jcr:content/folderThumbnail] does not exist anymore
	at org.apache.jackrabbit.oak.jcr.delegate.ItemDelegate.checkAlive(ItemDelegate.java:86) [org.apache.jackrabbit.oak-jcr:1.22.9]
	at org.apache.jackrabbit.oak.jcr.session.ItemImpl$ItemWriteOperation.checkPreconditions(ItemImpl.java:96) [org.apache.jackrabbit.oak-jcr:1.22.9]
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.prePerform(SessionDelegate.java:614) [org.apache.jackrabbit.oak-jcr:1.22.9]
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.performVoid(SessionDelegate.java:270) [org.apache.jackrabbit.oak-jcr:1.22.9]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.remove(NodeImpl.java:235) [org.apache.jackrabbit.oak-jcr:1.22.9]
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.delete(JcrResourceProvider.java:498) [org.apache.sling.jcr.resource:3.0.18]
	... 15 common frames omitted
29.04.2022 17:15:35.511 *ERROR* [pool-33-thread-3] com.adobe.acs.commons.fam.impl.ActionManagerImpl Caught exception in task: Unable to delete resource
org.apache.sling.api.resource.PersistenceException: Unable to delete resource
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.delete(JcrResourceProvider.java:500) [org.apache.sling.jcr.resource:3.0.18]
	at org.apache.sling.resourceresolver.impl.providers.stateful.AuthenticatedResourceProvider.delete(AuthenticatedResourceProvider.java:193) [org.apache.sling.resourceresolver:1.7.10]
	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.delete(ResourceResolverControl.java:413) [org.apache.sling.resourceresolver:1.7.10]
	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.copy(ResourceResolverControl.java:606) [org.apache.sling.resourceresolver:1.7.10]
	at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.copy(ResourceResolverImpl.java:1126) [org.apache.sling.resourceresolver:1.7.10]
	at com.adobe.acs.commons.mcp.impl.processes.renovator.MovingFolder.lambda$move$0(MovingFolder.java:79) [com.adobe.acs.acs-aem-commons-bundle:5.3.0]
	at com.adobe.acs.commons.fam.actions.Actions.lambda$retry$2(Actions.java:141) [com.adobe.acs.acs-aem-commons-bundle:5.3.0]
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:200) [com.adobe.acs.acs-aem-commons-bundle:5.3.0]
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.runActionAndLogErrors(ActionManagerImpl.java:167) [com.adobe.acs.acs-aem-commons-bundle:5.3.0]
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.lambda$deferredWithResolver$0(ActionManagerImpl.java:159) [com.adobe.acs.acs-aem-commons-bundle:5.3.0]
	at com.adobe.acs.commons.fam.impl.TimedRunnable.run(TimedRunnable.java:91) [com.adobe.acs.acs-aem-commons-bundle:5.3.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.jcr.InvalidItemStateException: This item [/content/dam/we-retail/en/activities/hiking-moved/jcr:content/folderThumbnail] does not exist anymore
	at org.apache.jackrabbit.oak.jcr.delegate.ItemDelegate.checkAlive(ItemDelegate.java:86) [org.apache.jackrabbit.oak-jcr:1.22.9]
	at org.apache.jackrabbit.oak.jcr.session.ItemImpl$ItemWriteOperation.checkPreconditions(ItemImpl.java:96) [org.apache.jackrabbit.oak-jcr:1.22.9]
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.prePerform(SessionDelegate.java:614) [org.apache.jackrabbit.oak-jcr:1.22.9]
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.performVoid(SessionDelegate.java:270) [org.apache.jackrabbit.oak-jcr:1.22.9]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.remove(NodeImpl.java:235) [org.apache.jackrabbit.oak-jcr:1.22.9]
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.delete(JcrResourceProvider.java:498) [org.apache.sling.jcr.resource:3.0.18]
	... 15 common frames omitted
```

### Links

NA

**Comment by davidjgonzalez** [comment]
AEM 6.5.12  (Vanilla)
ACS Commons: 5.3.0

@josephrignanese  - i was able to move a folder with a review task attached to it without issues.

![2022-05-02 at 2 57 PM](https://user-images.githubusercontent.com/1451868/166310223-12343c53-6d12-4adc-800c-cbb4a1658421.jpg)

I have no exceptions during this. Are you sure your repository is in a stable state? Do you get the same if you OOTB move the folder?

I did notice that Renovator does NOT adjust the review path's contentPath property value (so after the move it still points to the old non-existent path) - however, I checked OOTB Moving of a folder with a review task attached and its the same behavior as renovator (the task is now broken) so I imagine that this is not a supported use-case in AEM? 

If we were to enhance Renovator, i think we'd have to add a findReferences() to MovingFolder, and  part of that would be search for all review tasks w/ an affected contentPath.


[1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/renovator/MovingFolder.java

**Comment by josephrignanese** [comment]
Hi @davidjgonzalez - did you do a dry run or actual move? The screenshot looks to me like what you get for a dry run since you don't have a move time or other times populated.

**Comment by josephrignanese** [comment]
Hi @davidjgonzalez,

I'm uploading some more info, maybe it will help to reproduce.

Content package of folder with review task:
[src-asset-folder-with-review-task-1.0.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/8667258/src-asset-folder-with-review-task-1.0.zip)

MCP input values:

Source: /content/dam/we-retail/en/experiences/wester-australia-by-camper-van1
Destination: /content/dam/we-retail/en/experiences/wester-australia-by-camper-van1-moved
Max References: -1 (Default)
Publish: None
Create versions: Yes
Update status: Yes
Extensive ACL checks: No
Dry run: No
Audit Trails: No
Detailed Report: Yes

Screenshot of MCP process:
![Screen Shot 2022-05-11 at 4 21 47 pm](https://user-images.githubusercontent.com/17347917/167783544-fb7db9ba-96b7-4878-bc3d-3766c85ff7ea.png)

Content package from failed MCP process instance:
[renovator-failed-mcp-instance-1.0.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/8667286/renovator-failed-mcp-instance-1.0.zip)

AEM error.log during MCP run:
[renovator-failed-aem-error.log.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/8667284/renovator-failed-aem-error.log.zip)

**Comment by saikrishnalambo** [comment]
I was trying to move some of the assets, but i was getting the error like this. i think the renovator is stuck any one can help me?
![Screenshot (24)](https://user-images.githubusercontent.com/73388700/201059522-c48e79e3-2c8f-457d-a08b-d075b884cf58.png)

**Comment by saikrishnalambo** [comment]
i was trying to move the asset but i am facing the stuck issue here, can anyone help me
<img width="960" alt="Renovator" src="https://user-images.githubusercontent.com/73388700/201060088-55c5b714-407b-402d-96fc-df77c10ef552.png">

**Comment by at199** [comment]
A workaround: go to workflow instance. and terminate running workflows.
it did the job for me
