### ISSUE TITLE
AEMaaCS "/apps/acs-commons/components/utilities/errorpagehandler/404.jsp" not found on publisher

### ISSUE THREAD

**Issue by eagleinhills** [Adobe-Consulting-Services/acs-aem-commons#3007]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: __AEMaaCS_AEM RELEASE: 2022.11.9850.20221116T162329Z____
* [ ] ACS AEM Commons Version: _5.3.0____
* [ ] Reproducible on Latest? yes/no yes

### Expected Behavior
ACS commons has been added as embedded package:
In pom.xml for the all project:
`<embedded>
                            <groupId>com.adobe.acs</groupId>
                            <artifactId>acs-aem-commons-ui.apps</artifactId>
                            <type>zip</type>
                            <target>/apps/anaplan-packages/application/install</target>
                            <filter>true</filter>
                            <isAllVersionsFilter>true</isAllVersionsFilter>
                        </embedded>
                        <embedded>
                            <groupId>com.adobe.acs</groupId>
                            <artifactId>acs-aem-commons-ui.content</artifactId>
                            <type>zip</type>
                            <target>/apps/anaplan-packages/content/install</target>
                            <filter>true</filter>
                            <isAllVersionsFilter>true</isAllVersionsFilter>
                        </embedded>`

and in the core project pom.xml
`<dependency>
            <groupId>com.adobe.acs</groupId>
            <artifactId>acs-aem-commons-bundle</artifactId>
            <version>5.3.0</version>
            <scope>provided</scope>
        </dependency>`

ACS Common Error handler is configured following the steps in acs commons error handler documentation. It is working and showing the 404 page but acs commons code is not found on AEM Cloud Publishers and resulting in the following exceptions in the logs:
The exceptions I see in the logs is:

 org.apache.sling.scripting.jsp.jasper.JasperException: /apps/sling/servlet/errorhandler/404.jsp(2,2) File "/apps/acs-commons/components/utilities/errorpagehandler/404.jsp" not found

Full stack trace is below:

`17.12.2022 01:06:15.047 [cm-p64013-e772856-aem-publish-5d7bb5c8c9-b5snm] *ERROR* [3.99.200.83 [1671239175044] GET /content/anaplan/us/en/favicon.ico HTTP/1.1] org.apache.sling.servlets.resolver.internal.SlingServletResolver Original error null
17.12.2022 01:06:15.047 [cm-p64013-e772856-aem-publish-5d7bb5c8c9-b5snm] *ERROR* [3.99.200.83 [1671239175044] GET /content/anaplan/us/en/favicon.ico HTTP/1.1] org.apache.sling.engine.impl.DefaultErrorHandler Error handler failed:java.io.IOException
java.io.IOException: Error handler failed: org.apache.sling.api.scripting.ScriptEvaluationException
	at org.apache.sling.servlets.resolver.internal.SlingServletResolver.handleError(SlingServletResolver.java:657) [org.apache.sling.servlets.resolver:2.9.8]
	at org.apache.sling.servlets.resolver.internal.SlingServletResolver.handleError(SlingServletResolver.java:320) [org.apache.sling.servlets.resolver:2.9.8]
	at org.apache.sling.engine.impl.DefaultErrorHandler.handleError(DefaultErrorHandler.java:97) [org.apache.sling.engine:2.10.2]
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl$1.render(SlingRequestProcessorImpl.java:354) [org.apache.sling.engine:2.10.2]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:88) [org.apache.sling.engine:2.10.2]
	at org.apache.sling.rewriter.impl.RewriterFilter.doFilter(RewriterFilter.java:87) [org.apache.sling.rewriter:1.3.2]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78) [org.apache.sling.engine:2.10.2]
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:131) [org.apache.sling.i18n:2.5.18]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:78) [org.apache.sling.engine:2.10.2]
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.handleError(SlingRequestProcessorImpl.java:361) [org.apache.sling.engine:2.10.2]
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.doProcessRequest(SlingRequestProcessorImpl.java:165) [org.apache.sling.engine:2.10.2]
	at org.apache.sling.engine.impl.SlingMainServlet.service(SlingMainServlet.java:251) [org.apache.sling.engine:2.10.2]
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:126) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:86) [org.apache.felix.http.jetty:4.2.0]
	at com.adobe.granite.metrics.redimpl.REDMetricsServletFilter.doFilter(REDMetricsServletFilter.java:214) [com.adobe.granite.metrics.red:1.1.0]
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:149) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81) [org.apache.felix.http.jetty:4.2.0]
	at com.adobe.granite.metrics.knownerrors.impl.ReportingRequestFilter.doFilter(ReportingRequestFilter.java:100) [com.adobe.granite.metrics.knownerrors:0.0.24]
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:149) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81) [org.apache.felix.http.jetty:4.2.0]
	at com.adobe.granite.cors.impl.CORSFilter.doFilter(CORSFilter.java:87) [com.adobe.granite.cors:1.0.20]
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:149) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81) [org.apache.felix.http.jetty:4.2.0]
	at com.adobe.granite.license.impl.http.LicenseCheckFilter.doFilter(LicenseCheckFilter.java:301) [com.adobe.granite.license.http:1.0.0]
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:149) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:131) [org.apache.sling.i18n:2.5.18]
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:149) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.sling.featureflags.impl.FeatureManager.doFilter(FeatureManager.java:116) [org.apache.sling.featureflags:1.2.2]
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:149) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.sling.engine.impl.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:73) [org.apache.sling.engine:2.10.2]
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:149) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.sling.engine.impl.parameters.RequestParameterSupportConfigurer.doFilter(RequestParameterSupportConfigurer.java:67) [org.apache.sling.engine:2.10.2]
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:149) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.dispatch.Dispatcher$1.doFilter(Dispatcher.java:152) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager$2.doFilter(WhiteboardManager.java:1000) [org.apache.felix.http.jetty:4.2.0]
	at com.adobe.granite.auth.oauth.impl.OAuthCallbackFilter.doFilter(OAuthCallbackFilter.java:78) [com.adobe.granite.auth.oauth:1.9.4]
	at org.apache.felix.http.base.internal.handler.PreprocessorHandler.handle(PreprocessorHandler.java:137) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager$2.doFilter(WhiteboardManager.java:1006) [org.apache.felix.http.jetty:4.2.0]
	at com.adobe.granite.auth.ims.impl.IMSClusterExchangeTokenPreprocessor.doFilter(IMSClusterExchangeTokenPreprocessor.java:241) [com.adobe.granite.auth.ims:1.4.36]
	at org.apache.felix.http.base.internal.handler.PreprocessorHandler.handle(PreprocessorHandler.java:137) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager$2.doFilter(WhiteboardManager.java:1006) [org.apache.felix.http.jetty:4.2.0]
	at com.adobe.granite.cors.impl.CORSFilter.doFilter(CORSFilter.java:87) [com.adobe.granite.cors:1.0.20]
	at org.apache.felix.http.base.internal.handler.PreprocessorHandler.handle(PreprocessorHandler.java:137) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager$2.doFilter(WhiteboardManager.java:1006) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.sling.security.impl.ReferrerFilter.doFilter(ReferrerFilter.java:323) [org.apache.sling.security:1.1.24]
	at org.apache.felix.http.base.internal.handler.PreprocessorHandler.handle(PreprocessorHandler.java:137) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager$2.doFilter(WhiteboardManager.java:1006) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:97) [org.apache.felix.http.sslfilter:1.2.6]
	at org.apache.felix.http.base.internal.handler.PreprocessorHandler.handle(PreprocessorHandler.java:137) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager$2.doFilter(WhiteboardManager.java:1006) [org.apache.felix.http.jetty:4.2.0]
	at com.adobe.granite.probes.impl.ProbesPreprocessor.doFilter(ProbesPreprocessor.java:58) [com.adobe.granite.probes:1.0.12]
	at org.apache.felix.http.base.internal.handler.PreprocessorHandler.handle(PreprocessorHandler.java:137) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager$2.doFilter(WhiteboardManager.java:1006) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager.invokePreprocessors(WhiteboardManager.java:1010) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:94) [org.apache.felix.http.jetty:4.2.0]
	at org.apache.felix.http.base.internal.dispatch.DispatcherServlet.service(DispatcherServlet.java:49) [org.apache.felix.http.jetty:4.2.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [org.apache.felix.http.servlet-api:1.2.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [org.apache.felix.http.jetty:4.2.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [org.apache.felix.http.jetty:4.2.0]
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.sling.api.scripting.ScriptEvaluationException: /apps/sling/servlet/errorhandler/404.jsp(2,2) File "/apps/acs-commons/components/utilities/errorpagehandler/404.jsp" not found
	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.wrapException(JspServletWrapper.java:608) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:670) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:472) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.JspScriptEngineFactory$JspScriptEngine.callJsp(JspScriptEngineFactory.java:500) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.JspScriptEngineFactory$JspScriptEngine.eval(JspScriptEngineFactory.java:582) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:395) [org.apache.sling.scripting.core:2.4.8]
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.eval(DefaultSlingScript.java:191) [org.apache.sling.scripting.core:2.4.8]
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:500) [org.apache.sling.scripting.core:2.4.8]
	at org.apache.sling.servlets.resolver.internal.SlingServletResolver.handleError(SlingServletResolver.java:644) [org.apache.sling.servlets.resolver:2.9.8]
	... 92 common frames omitted
Caused by: org.apache.sling.scripting.jsp.jasper.JasperException: /apps/sling/servlet/errorhandler/404.jsp(2,2) File "/apps/acs-commons/components/utilities/errorpagehandler/404.jsp" not found
	at org.apache.sling.scripting.jsp.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:40) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:407) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:132) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.compiler.Parser.processIncludeDirective(Parser.java:332) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.compiler.Parser.parseIncludeDirective(Parser.java:367) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.compiler.Parser.parseDirective(Parser.java:459) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.compiler.Parser.parseElements(Parser.java:1417) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.compiler.Parser.parse(Parser.java:133) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.compiler.ParserController.doParse(ParserController.java:215) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.compiler.ParserController.parse(ParserController.java:103) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.compiler.Compiler.generateJava(Compiler.java:154) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.compiler.Compiler.compile(Compiler.java:292) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.JspCompilationContext.compile(JspCompilationContext.java:515) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.prepareServlet(JspServletWrapper.java:444) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:505) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:464) [org.apache.sling.scripting.jsp:2.6.0]
	... 98 common frames omitted`

**Comment by davidjgonzalez** [comment]
Can you please verify it is not on AEM CS Publish using AEM CS Repository Browser? is anything under /apps/acs-commons ?

https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/debugging/debugging-aem-as-a-cloud-service/repository-browser.html

**Comment by eagleinhills** [comment]
David, No, I don't see it. Even the /apps/acs-commons is missing. I thought using Embedded package will install it but looks like it did not work. Any ideas how to fix it?

Here is the all project's pom.xml

`<embedded>
    <groupId>com.adobe.acs</groupId>
    <artifactId>acs-aem-commons-ui.apps</artifactId>
    <type>zip</type>
    <target>/apps/anaplan-packages/application/install</target>
    <filter>true</filter>
    <isAllVersionsFilter>true</isAllVersionsFilter>
</embedded>
<embedded>
    <groupId>com.adobe.acs</groupId>
    <artifactId>acs-aem-commons-ui.content</artifactId>
    <type>zip</type>
    <target>/apps/anaplan-packages/content/install</target>
    <filter>true</filter>
    <isAllVersionsFilter>true</isAllVersionsFilter>
</embedded> 

and the core pom.xml 

<dependency>
            <groupId>com.adobe.acs</groupId>
            <artifactId>acs-aem-commons-bundle</artifactId>
            <version>5.3.0</version>
            <scope>provided</scope>
        </dependency>`

**Comment by davidjgonzalez** [comment]
@eagleinhills that should work - but you should be embedding ACS Commons' "all" package which is named "content" for historical reasons.

see: https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html

**Comment by eagleinhills** [comment]
@davidjgonzalez Thank you for pointing me to the https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html

The issue is resolved.

Package filter was alright. I was missing the dependency below in the all project pom.xml:
```
<dependency>
    <groupId>com.adobe.acs</groupId>
    <artifactId>acs-aem-commons-content</artifactId>
    <version>5.4.0</version>
    <type>zip</type>
</dependency>
```
So the all project pom.xml has:

```
<embedded>
    <groupId>com.adobe.acs</groupId>
    <artifactId>acs-aem-commons-content</artifactId>
    <type>zip</type>
    <target>/apps/anaplan-packages/content/install</target>
    <filter>true</filter>
    <isAllVersionsFilter>true</isAllVersionsFilter>
</embedded>

And the dependency 

<dependency>
    <groupId>com.adobe.acs</groupId>
    <artifactId>acs-aem-commons-content</artifactId>
    <version>5.4.0</version>
    <type>zip</type>
</dependency>

```

and the core project pom.xml has:

```
<dependency>
    <groupId>com.adobe.acs</groupId>
    <artifactId>acs-aem-commons-bundle</artifactId>
    <version>5.4.0</version>
    <scope>provided</scope>
</dependency>
```
