### ISSUE TITLE
Cloud Manager Deployment failure with latest AEM CS version

### ISSUE THREAD

**Issue by shibinose** [Adobe-Consulting-Services/acs-aem-commons#3032]
## Required Information

* [ v2023.1.10675.20230113T110236Z-220900] AEM Version
* [ v5.3.2] ACS AEM Commons Version: _____
* [Yes ] Reproducible on Latest? yes/no

### Expected Behavior

Cloud Manager Deployment Should be successful

### Actual Behavior
We get the below error during the Build Image Step. 
25.01.2023 05:27:35.596 *INFO* [Apache Sling Repository Startup Thread #1] org.apache.jackrabbit.vault.packaging.impl.ActivityLog adobe/consulting:acs-aem-commons-content:5.3.2-cp2fm-converted: EXTRACT
25.01.2023 05:27:45.867 *INFO* [Apache Sling Repository Startup Thread #1] org.apache.jackrabbit.vault.packaging.impl.ActivityLog com.tccc.dam:tccc-dam.ui.apps:1.0.38-SNAPSHOT-cp2fm-converted: EXTRACT
25.01.2023 05:27:45.882 *INFO* [Apache Sling Repository Startup Thread #1] org.apache.jackrabbit.vault.packaging.impl.ActivityLog com.tccc.dam:tccc-dam.ui.config:1.0.38-SNAPSHOT-cp2fm-converted: EXTRACT
25.01.2023 05:27:45.883 *ERROR* [Apache Sling Repository Startup Thread #1] com.adobe.granite.repository.impl.SlingRepositoryManager Exception in a SlingRepositoryInitializer, SlingRepository service registration aborted
java.lang.IllegalStateException: Excecutionplan execution contained errors - cannot complete repository initialization.
	at org.apache.sling.jcr.packageinit.impl.ExecutionPlanRepoInitializer.processRepository(ExecutionPlanRepoInitializer.java:168)
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.executeRepositoryInitializers(AbstractSlingRepositoryManager.java:627)
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.initializeAndRegisterRepositoryService(AbstractSlingRepositoryManager.java:575)
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.access$300(AbstractSlingRepositoryManager.java:96)
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager$4.run(AbstractSlingRepositoryManager.java:544)
	Suppressed: java.io.IOException: javax.jcr.nodetype.ConstraintViolationException: OakConstraint0025: /apps/settings/dam[[nt:folder, rep:AccessControllable]]: Unexpected child node search found in a new node
		at org.apache.jackrabbit.vault.packaging.registry.impl.FSPackageRegistry.installPackage(FSPackageRegistry.java:642)
_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

**Comment by YegorKozlov** [comment]
The latest release 5.5.2 installs just fine to me.

**Comment by shibinose** [comment]
The /apps/settings/dam node path from acs-commons is of type nt:folder.  We have another embedd dependency in our code which also overlayed /apps/settings/dam(cq:Page) with an nt:unstructured node inside it.
As the cloud manager deployment pipeline runs with latest AEM CS version(2023.1.10912.20230130T173736Z), I think there is a conflict happening during the "Build Image" step, which use "nt:folder" type to create /apps/settings/dam and the "nt:unstructured" node can not be added inside "nt"folder". This causes the failure in "Build Image" step.

Is it possible to make the "/apps/settings/dam" node of type "cq:Page" in acs-commons which should ideally fix this issue ?

**Comment by shibinose** [comment]
Also, fyi that the issue is not reproducible with local SDK. It happens only when AEM Cloud Service deployment happens through Cloud Manager.

**Comment by davidjgonzalez** [comment]
Is there a node at /libs/settings/dam? If so, what node type?

What package is creating it as cq:Page?

**Comment by shibinose** [comment]
Yes, /libs/settings/dam is of type cq:Page.

We are using a 3rd party embedd dependency package with some customization on Assets Admin Search Rail for a adding a new Facet.
