### ISSUE TITLE
[Health Check] Disable ACS AEM Commons SMTP Health Check

### ISSUE THREAD

**Issue by hiralvasa** [Adobe-Consulting-Services/acs-aem-commons#3065]
Hi Experts,

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: __6.5.6.0)_____
* [ ] ACS AEM Commons Version: __4.5.0___
* [ ] Reproducible on Latest? yes/no

### Expected Behavior
Is there a way to disable "ACS AEM Commons SMTP Health Check"? 

### Actual Behavior
After the removal of the 'Test E-mail Address' value from the "com.adobe.acs.commons.hc.impl.SMTPMailServiceHealthCheck" configuration, ACS AEM Commons SMTP Health Check gets triggered every minute with the following error : 

```
com.adobe.acs.commons.hc.impl.SMTPMailServiceHealthCheck Unable to execute E-mail health check
javax.mail.internet.AddressException: Illegal address
	at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:122) [javax.mail:1.6.2]
	at com.adobe.acs.commons.hc.impl.SMTPMailServiceHealthCheck.execute(SMTPMailServiceHealthCheck.java:118) [com.adobe.acs.acs-aem-commons-bundle:4.5.0]
	at com.adobe.granite.queries.impl.hc.QueryHealthCheckMetrics$LazyGauge.execute(QueryHealthCheckMetrics.java:273) [com.adobe.granite.queries:1.0.77.CQ650-B0002]
	at com.adobe.granite.queries.impl.hc.QueryHealthCheckMetrics$LazyGauge.lambda$new$0(QueryHealthCheckMetrics.java:260) [com.adobe.granite.queries:1.0.77.CQ650-B0002]
	at org.apache.sling.commons.scheduler.impl.QuartzJobExecutor.execute(QuartzJobExecutor.java:347) [org.apache.sling.commons.scheduler:2.7.2]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org.apache.sling.commons.scheduler:2.7.2]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Please help me to understand if SMTP Health Check isn't executed as part of Health Check Status E-mailer, then how is it being triggered every minute?

Thanks in advance!
Hiral Vasa

**Comment by davidjgonzalez** [comment]
@hiralvasa  can you check to see if SMTPMailServiceHealthCheck is active/satisfied in /system/console/components

Make sure you DELETE the config, not just clear out value.

if you delete it's OSGI config, it should not be registered in AEM anymore (as an OSGI config is required)

**Comment by hiralvasa** [comment]
Hi @davidjgonzalez,
Thanks for the quick reply.
SMTPMailServiceHealthCheck component is in active state and also it works well after deleting the config.

Wanted to understand - is there a way to update the cron expression for the STMP health check service alone? Currently, it is being triggered every minute, whereas I am looking for something like weekly once.

Thanks in advance!
Hiral Vasa

**Comment by davidjgonzalez** [comment]
in v6.0.6 updated the HC to default to once every 24 hours when enabled. You should still figure out why/how you've enabled it tho.
