### ISSUE TITLE
This Project's Github Action JDK 21 builds fail

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#3213]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: N/A
* [X] ACS AEM Commons Version:  Latest
* [X] Reproducible on Latest? yes

See errors in:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/actions/runs/6882972329

### Expected Behavior

The build should work.

### Actual Behavior

The JDK 21 builds fail.

**Comment by davidjgonzalez** [comment]
@kwin  do we need JDK 21? All the JDK 21 builds are failing in github actions.

**Comment by kwin** [comment]
The failing test is

```
[INFO] Running com.adobe.acs.commons.data.VariantTest
Error:  Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in com.adobe.acs.commons.data.VariantTest
Error:  com.adobe.acs.commons.data.VariantTest.calendarConversion  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.util.Date.getTime()" because the return value of "com.adobe.acs.commons.data.Variant.convert(Object, java.lang.Class)" is null
	at com.adobe.acs.commons.data.VariantTest.calendarConversion(VariantTest.java:78)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:362)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Currently I fail to reproduce locally with Temurin 21.0.1

**Comment by kwin** [comment]
I can reproduce the isue with default locale being `en_US` (I had language `de` before as default`).

**Comment by kwin** [comment]
Here are the formatter used with different JDKs and default locales


```
JDK 21.0.1 de_US

[FastDateFormat[dd.MM.yy,de_US,Europe/Berlin],
FastDateFormat[d. MMMM y,de_US,Europe/Berlin],
FastDateFormat[HH:mm,de_US,Europe/Berlin], this matches "12:00 AM"
FastDateFormat[HH:mm:ss z,de_US,Europe/Berlin],
FastDateFormat[dd.MM.yy, HH:mm,de_US,Europe/Berlin],  
FastDateFormat[d. MMMM y, HH:mm,de_US,Europe/Berlin],
FastDateFormat[dd.MM.yy, HH:mm:ss z,de_US,Europe/Berlin],
FastDateFormat[d. MMMM y, HH:mm:ss z,de_US,Europe/Berlin],
FastDateFormat[EEEE, d. MMMM y, HH:mm:ss zzzz,de_US,Europe/Berlin],
FastDateFormat[yyyy-MM-dd'T'HH:mm:ss.SSSXXX,de_US,Europe/Berlin]]

JDK 21.0.1 en_US (not matching "12:00 AM")

[FastDateFormat[M/d/yy,en_US,Europe/Berlin],
FastDateFormat[MMMM d, y,en_US,Europe/Berlin],
FastDateFormat[h:mm a,en_US,Europe/Berlin],
FastDateFormat[h:mm:ss a z,en_US,Europe/Berlin],
FastDateFormat[M/d/yy, h:mm a,en_US,Europe/Berlin],
FastDateFormat[MMMM d, y, h:mm a,en_US,Europe/Berlin],
FastDateFormat[M/d/yy, h:mm:ss a z,en_US,Europe/Berlin],
FastDateFormat[MMMM d, y, h:mm:ss a z,en_US,Europe/Berlin],
FastDateFormat[EEEE, MMMM d, y, h:mm:ss a zzzz,en_US,Europe/Berlin],
FastDateFormat[yyyy-MM-dd'T'HH:mm:ss.SSSXXX,en_US,Europe/Berlin]]

JDK 17.0.7 en_US

[FastDateFormat[M/d/yy,en_US,Europe/Berlin],
FastDateFormat[MMMM d, y,en_US,Europe/Berlin],
FastDateFormat[h:mm a,en_US,Europe/Berlin], // this matches "12:00 AM"
FastDateFormat[h:mm:ss a z,en_US,Europe/Berlin],
FastDateFormat[M/d/yy, h:mm a,en_US,Europe/Berlin],
FastDateFormat[MMMM d, y, h:mm a,en_US,Europe/Berlin],
FastDateFormat[M/d/yy, h:mm:ss a z,en_US,Europe/Berlin],
FastDateFormat[MMMM d, y 'at' h:mm:ss a z,en_US,Europe/Berlin],
FastDateFormat[EEEE, MMMM d, y 'at' h:mm:ss a zzzz,en_US,Europe/Berlin],
FastDateFormat[yyyy-MM-dd'T'HH:mm:ss.SSSXXX,en_US,Europe/Berlin]]
```

For some reason the formatter `FastDateFormat[h:mm a,en_US,Europe/Berlin]` can no longer parse `12:00 AM` in JDK21. Not sure why yet, but date formats may change with each major JDK release and currently the date format does not even set a stable local nor timezone, therefore the tests may easily fail on different combinations. Not sure what format should actually be supported by `Variant`. @YegorKozlov or @davidjgonzalez Any idea here?

**Comment by YegorKozlov** [comment]
a curious case. @kwin I also debugged it down to the unicode space in the parsed pattern when I saw your commit.

**Comment by YegorKozlov** [comment]
@kwin FYI, JDK 23 will allow loose matching of spaces when parsing date/time strings

https://inside.java/2024/03/29/quality-heads-up/

> The JDK update to CLDR version 42 included a change where regular spaces in date/time formats (and some other formatted values) were replaced with (narrow) non-breaking spaces. This lead to issues for existing code that relied on parsing such strings. To address that, JDK 23 allows loose matching of spaces when parsing date/time strings. Loose matching is performed in the lenient parsing style for both date/time parsers in `java.time.format` and `java.text` packages. In the default strict parsing style, those spaces are considered distinct as before.

**Comment by kwin** [comment]
@YegorKozlov Thanks for the info. Stumbled across this blog post as well. Unfortunately the only solution for Java < 23 is using the legacy parameter `-Djava.locale.providers=COMPAT`...
