### ISSUE TITLE
ACS commons | Garbage collection scheduler failing

### ISSUE THREAD

**Issue by Shyam1814** [Adobe-Consulting-Services/acs-aem-commons#3261]
## Required Information

[AEM6.5 , service pack 6.5.12.0 ]
[ACS commons version : 5.6.0 ]
[ yes]

### Expected Behavior

As described per the article (https://adobe-consulting-services.github.io/acs-aem-commons/features/package-garbage-collector/index.html) created the osgiConfig with values
![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/149077156/a2c7db8d-7500-46d6-9fcb-1169754804ac).

and it is expected to delete package in mentioned group to be deleted if its less than 30 days old.

### Actual Behavior

Its failing with null pointer exception
![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/149077156/d5e27ff4-af71-4cb7-ab53-2bfc76f75598)

### Steps to Reproduce

follow the steps mentioned in document.
https://adobe-consulting-services.github.io/acs-aem-commons/features/package-garbage-collector/index.html

### Links
exact log:

19.02.2024 14:28:08.505 *ERROR* [sling-threadpool-850d2e77-5fd2-4285-8f71-3ab3331dd6f7-(apache-sling-job-thread-pool)-17-Package Garbage Collection Queue(com/adobe/acs/commons/PackageGarbageCollectionJob)] org.apache.sling.event.impl.jobs.queues.JobQueueImpl.Package Garbage Collection Queue Unhandled error occured in job processor null while processing job Sling Job [topic=com/adobe/acs/commons/PackageGarbageCollectionJob, id=2024/2/19/14/28/66ed07ef-eab4-43af-8597-db7a155976dc_366561, properties=slingevent:application=66ed07ef-eab4-43af-8597-db7a155976dc,jcr:created=java.util.GregorianCalendar(Mon Feb 19 14:28:00 UTC 2024),slingevent:created=java.util.GregorianCalendar(Mon Feb 19 14:28:00 UTC 2024),event.job.queuename=Package Garbage Collection Queue,event.job.queued.time=java.util.GregorianCalendar(Mon Feb 19 14:28:00 UTC 2024),jcr:createdBy=sling-event,sling:resourceType=slingevent:Job,event.job.application=66ed07ef-eab4-43af-8597-db7a155976dc,maxAgeInDays=30,groupName=com.rockwell.aem,event.job.retries=10,event.job.started.time=java.util.GregorianCalendar(Mon Feb 19 14:28:00 UTC 2024),jcr:primaryType=slingevent:Job,event.job.retrycount=0,:sling:jobs:asynchandler=org.apache.sling.event.impl.jobs.JobConsumerManager$JobConsumerWrapper$1@60fbf00e]
java.lang.NullPointerException: null
	at java.util.Calendar.getMillisOf(Calendar.java:3405)
	at java.util.Calendar.compareTo(Calendar.java:2784)
	at java.util.Calendar.compareTo(Calendar.java:313)
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
	at java.util.function.BinaryOperator.lambda$maxBy$1(BinaryOperator.java:74)
	at java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
	at java.util.stream.ReferencePipeline.max(ReferencePipeline.java:515)
	at com.adobe.acs.commons.packagegarbagecollector.PackageGarbageCollectionJob.isLatestInstalled(PackageGarbageCollectionJob.java:118) [com.adobe.acs.acs-aem-commons-bundle:5.6.0]
	at com.adobe.acs.commons.packagegarbagecollector.PackageGarbageCollectionJob.process(PackageGarbageCollectionJob.java:92) [com.adobe.acs.acs-aem-commons-bundle:5.6.0]
	at org.apache.sling.event.impl.jobs.JobConsumerManager$JobConsumerWrapper.process(JobConsumerManager.java:502) [org.apache.sling.event:4.2.24]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.startJob(JobQueueImpl.java:351) [org.apache.sling.event:4.2.24]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.access$100(JobQueueImpl.java:60) [org.apache.sling.event:4.2.24]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl$1.run(JobQueueImpl.java:287) [org.apache.sling.event:4.2.24]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Analysis:
 function from class PackageGarbageCollectionJob:

 private boolean isLatestInstalled(JcrPackage jcrPackage, List<JcrPackage> installedPackages) {
        **Optional<JcrPackage> lastInstalledPackageOptional = installedPackages.stream().filter(installedPackage -> {
            PackageDefinition definition = new PackageDefinition(installedPackage);
            return definition.isSameNameAndGroup(jcrPackage);
        }).max(Comparator.comparing(pkg -> new PackageDefinition(pkg).getLastUnpacked()));**

        if (lastInstalledPackageOptional.isPresent()) {
            JcrPackage lastInstalledPackage = lastInstalledPackageOptional.get();
            PackageDefinition lastInstalledPackageDefinition = new PackageDefinition(lastInstalledPackage);
            PackageDefinition thisPackageDefinition = new PackageDefinition(jcrPackage);

            // If it's not actually installed yet.
            if (lastInstalledPackageDefinition.getLastUnpacked() == null) {
                return false;
            }

            return lastInstalledPackageDefinition.hasSamePid(thisPackageDefinition);
        }

        return false;
    }
  
lines mentioned in bold are responsible for the code break as max function uses the reducer and it expect at least single value after filtering packages. And negative scenario is not handled here.

**Comment by davidjgonzalez** [comment]
Hi this was resolved a while ago (i believe 6.3.4, but that has a different bug that as then fixed in 6.3.6)
