### ISSUE TITLE
ACS composite multifield error prevents to load values in the nested fields on author dialog.

### ISSUE THREAD

**Issue by VivekVikranth** [Adobe-Consulting-Services/acs-aem-commons#3263]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.19
* [ ] ACS AEM Commons Version: 6.3.6
* [ ] Reproducible on Latest? yes

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen.
In AEM author dialog nested multifield should load with pre-existing or saved data.

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens.
AEM author values not being displayed inside multifields used in our website's page properties and Global Content properties

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_
After the latest AEM version upgrade and ACS version upgrade to 6.3.6 from 5.5.2

Getting following error in console

Uncaught TypeError: Cannot read properties of undefined (reading 'isEmpty')
    at instanceGenerator.addDataInFields (composite-multifield.min.js:17:365)
    at HTMLDocument.<anonymous> (composite-multifield.min.js:25:108)

This composite-multifield.js is not directly loaded via our codebase. So not able to debug its configuration.

### Links

_Links to related assets, e.g. content packages containing test components
No links

**Comment by csaboka** [comment]
@VivekVikranth #3265 has been accepted and is part of the latest release. Since your issue sounds similar to the one covered by the PR, it might already be fixed in the latest release.
