### ISSUE TITLE
Discovery-AsyncEventSender] org.apache.sling.discovery.commons.providers.base.AsyncTopologyEvent trigger: handler threw exception

### ISSUE THREAD

**Issue by VishalBansal1508** [Adobe-Consulting-Services/acs-aem-commons#3290]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc.: AEM cloud
* [ ] ACS AEM Commons Version: 5.1.2_____
* [ ] Reproducible on Latest? yes/no YES

### Expected Behavior

Warning should not occurred 

### Actual Behavior

Given warning :*WARN* [Discovery-AsyncEventSender] org.apache.sling.discovery.commons.providers.base.AsyncTopologyEvent trigger: handler threw exception. handler: [com.adobe.acs.commons.util.impl.DiscoveryServiceHelper@44139618](mailto:com.adobe.acs.commons.util.impl.DiscoveryServiceHelper@44139618), exception: java.lang.IllegalStateException: Invalid BundleContext.
java.lang.IllegalStateException: Invalid BundleContext. [Seen in author error log]

### Steps to Reproduce

In AEM author logs warning appered.

### Links 
This fixed as per blog : [https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2492] but still we can see this error in logs.

**Comment by joerghoh** [comment]
can confirm this issue with 6.12.0 on AEM CS.

**Comment by drj101687** [comment]
can confirm this issue with 6.16.0 on AEM CS.

```*WARN* [Discovery-AsyncEventSender] org.apache.sling.discovery.commons.providers.base.AsyncTopologyEvent trigger: handler threw exception. handler: com.adobe.acs.commons.util.impl.DiscoveryServiceHelper@420fe447, exception: java.lang.IllegalStateException: Invalid BundleContext.
java.lang.IllegalStateException: Invalid BundleContext.
	at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:491)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:308)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:335)
	at com.adobe.acs.commons.util.impl.DiscoveryServiceHelper.registerClusterLeader(DiscoveryServiceHelper.java:69) [com.adobe.acs.acs-aem-commons-bundle:6.16.0]
	at com.adobe.acs.commons.util.impl.DiscoveryServiceHelper.handleTopologyEvent(DiscoveryServiceHelper.java:50) [com.adobe.acs.acs-aem-commons-bundle:6.16.0]
	at org.apache.sling.discovery.commons.providers.base.AsyncTopologyEvent.trigger(AsyncTopologyEvent.java:53) [org.apache.sling.discovery.commons:1.1.0]
	at org.apache.sling.discovery.commons.providers.base.AsyncEventSender.run(AsyncEventSender.java:118) [org.apache.sling.discovery.commons:1.1.0]
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by kwin** [comment]
Anyone can come up with a PR fixing this?
