### ISSUE TITLE
CreateRedirectConfigurationServlet throws Exception when ancestor node types are different than expected

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#3398]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 2024.7.17098.20240711T134106Z
* [X] ACS AEM Commons Version: 6.6.2
* [X] Reproducible on Latest? yes

### Expected Behavior

Creating redirects should work also when the ancestor CAC nodes have an unexpected node type

### Actual Behavior

The following exception can be seen:
```
4.07.2024 08:36:54.158 [cm-p124459-e1227496-aem-author-7656cddfd4-pnh4w] *ERROR* [x.x.x.x [1721810214111] POST /apps/acs-commons/content/redirect-manager/redirects/_jcr_content.create.html HTTP/1.1] com.adobe.acs.commons.redirects.servlets.CreateRedirectConfigurationServlet failed to create configuration org.apache.sling.api.resource.PersistenceException: Unable to commit changes to session. at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.commit(JcrResourceProvider.java:619) [org.apache.sling.jcr.resource:3.3.2] at org.apache.sling.resourceresolver.impl.providers.stateful.AuthenticatedResourceProvider.commit(AuthenticatedResourceProvider.java:247) [org.apache.sling.resourceresolver:1.11.6] at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.commit(ResourceResolverControl.java:531) [org.apache.sling.resourceresolver:1.11.6] at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.commit(ResourceResolverImpl.java:1030) [org.apache.sling.resourceresolver:1.11.6]
...
Caused by: org.apache.jackrabbit.oak.api.CommitFailedException: OakConstraint0001: /conf/hcp-plus/settings[[nt:folder]]: No matching definition found for child node redirects with effective type [nt:unstructured] at org.apache.jackrabbit.oak.plugins.nodetype.TypeEditor$1.onConstraintViolation(TypeEditor.java:109) [org.apache.jackrabbit.oak-core:1.66.0]
```

### Steps to Reproduce

Just have a CAC entry node `settings` of type `nt:folder` and then try to create redirects below.

### Proposed Fix

Create the redirects node as type `sling:Folder` instead of `nt:unstructured` because the former can be created below `nt:folder` while the latter cannot. The type is set in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/8c3533026031876a0437f526cbc817e51e581928/bundle/src/main/java/com/adobe/acs/commons/redirects/servlets/CreateRedirectConfigurationServlet.java#L100

**Comment by YegorKozlov** [comment]
I'm fine to change it to sling:Folder as long as it does not break things. Are we talking about the redirect nodes only, or the parent folder as well? Changing the type of the parent *might* break some things, like, ordering via dragging in the ui.

**Comment by kwin** [comment]
The parent is already created as `sling:Folder` (https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/8c3533026031876a0437f526cbc817e51e581928/bundle/src/main/java/com/adobe/acs/commons/redirects/servlets/CreateRedirectConfigurationServlet.java#L92) if it does not exist yet!
