### ISSUE TITLE
ErrorPageHandler fails; /apps/acs-commons/components/utilities/errorpagehandler/default.jsp contains double &&

### ISSUE THREAD

**Issue by FrankdeGrootPerficient** [Adobe-Consulting-Services/acs-aem-commons#3468]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.21
* [ ] ACS AEM Commons Version: 6.9.3
* [ ] Reproducible on Latest? yes

### Expected Behavior

ErrorPageHandler works

### Actual Behavior

ErrorPageHandler does not work; error.log shows 

```
Syntax error on token "&&", delete this token
25: 
26:     final ErrorPageHandlerService errorPageHandlerService = sling.getService(ErrorPageHandlerService.class);
27: 
28:     if (errorPageHandlerService != null && errorPageHandlerService.isEnabled() && && errorPageHandlerService.shouldRequestUseErrorPageHandler(slingRequest)) {
29:         final int status = errorPageHandlerService.getStatusCode(slingRequest);
30: 
31:         if (status >= SlingHttpServletResponse.SC_INTERNAL_SERVER_ERROR &&

	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.wrapException(JspServletWrapper.java:608) [org.apache.sling.scripting.jsp:2.6.0]
	at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:670) [org.apache.sling.scripting.jsp:2.6.0]
```

### Steps to Reproduce

Enable error page handler, create an error condition, see the problem. Or look at the code at /apps/acs-commons/components/utilities/errorpagehandler/default.jsp

**Comment by davidjgonzalez** [comment]
Fixed in 6.9.4
