### ISSUE TITLE
ACS AEM Commons Workflow Remover bug

### ISSUE THREAD

**Issue by boser87** [Adobe-Consulting-Services/acs-aem-commons#663]
Hi,
we are experiencing a bug affecting the workflow remover by ACS AEM Commons version 2.2.4. After running the purge from the UI (/etc/acs-commons/workflow-remover.html) we have the following exception. This bug should have been fixed in version 2.0.0 (https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/506), but apparently something is still not working.

Thank you.

`03.02.2016 11:46:30.800 *ERROR* [172.31.19.107 [1454496390796] POST /etc/acs-commons/workflow-remover/_jcr_content.remove.json HTTP/1.1] com.adobe.acs.commons.workflow.bulk.removal.impl.servlets.RemoveServlet An error occurred while attempting to remove workflow instances.
java.lang.NumberFormatException: For input string: "server0"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:580)
at java.lang.Integer.valueOf(Integer.java:766)
at com.adobe.acs.commons.workflow.bulk.removal.impl.WorkflowInstanceFolderComparator.compare(WorkflowInstanceFolderComparator.java:75)
at com.adobe.acs.commons.workflow.bulk.removal.impl.WorkflowInstanceFolderComparator.compare(WorkflowInstanceFolderComparator.java:64)
at com.adobe.acs.commons.workflow.bulk.removal.impl.WorkflowInstanceFolderComparator.compare(WorkflowInstanceFolderComparator.java:30)
at java.util.TreeMap.put(TreeMap.java:552)
at java.util.TreeSet.add(TreeSet.java:255)
at com.adobe.acs.commons.workflow.bulk.removal.impl.WorkflowInstanceRemoverImpl.getSortedAndFilteredFolders(WorkflowInstanceRemoverImpl.java:328)
at com.adobe.acs.commons.workflow.bulk.removal.impl.WorkflowInstanceRemoverImpl.removeWorkflowInstances(WorkflowInstanceRemoverImpl.java:169)
at com.adobe.acs.commons.workflow.bulk.removal.impl.servlets.RemoveServlet.doPost(RemoveServlet.java:130)
at org.apache.sling.api.servlets.SlingAllMethodsServlet.mayService(SlingAllMethodsServlet.java:148)
at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:344)
at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:375)
at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:533)
at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:45)
at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:64)
at com.day.cq.personalization.impl.TargetComponentFilter.doFilter(TargetComponentFilter.java:96)
at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
at com.day.cq.wcm.core.impl.WCMDebugFilter.doFilterWithErrorHandling(WCMDebugFilter.java:182)
at com.day.cq.wcm.core.impl.WCMDebugFilter.doFilter(WCMDebugFilter.java:149)
at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
at com.day.cq.wcm.core.impl.WCMComponentFilter.filterRootInclude(WCMComponentFilter.java:357)
at com.day.cq.wcm.core.impl.WCMComponentFilter.doFilter(WCMComponentFilter.java:166)
at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processComponent(SlingRequestProcessorImpl.java:282)
at org.apache.sling.engine.impl.filter.RequestSlingFilterChain.render(RequestSlingFilterChain.java:49)
at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:64)
at com.adobe.cq.dam.webdav.impl.io.DamWebdavRequestFilter.doFilter(DamWebdavRequestFilter.java:121)
at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
at com.adobe.granite.resourceresolverhelper.impl.ResourceResolverHelperImpl.doFilter(ResourceResolverHelperImpl.java:81)
at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)
at com.adobe.cq.dam.s7imaging.impl.auth.MemoryTokenAuthHandler.doFilter(MemoryTokenAuthHandler.java:156)`

**Comment by cpilsworth** [comment]
Have you got some YYYY-MM-DD folders alongside serverN folders?  The code expects dated workflow instance folders to be _beneath_ the serverN folder or in the place of (for older AEM/CQ instances).

The problem seems to be with [WorkflowInstanceRemoverImpl.getWorkflowInstanceFolders](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/8e4002bf1f8ebc3bfebe7df9a12a003ba0d1a9fe/bundle/src/main/java/com/adobe/acs/commons/workflow/bulk/removal/impl/WorkflowInstanceRemoverImpl.java#L447-L451) 
```
     if (NN_SERVER_FOLDER_PATTERN.matcher(resource.getName()).matches()) {
                folders.add(resource);
            } else if (!addedRoot && NN_DATE_FOLDER_PATTERN.matcher(resource.getName()).matches()) {
                folders.add(root);
                addedRoot = true;
            }
```
If a dated folder is found before the serverN folder, the root (/etc/workflow/instances) is added, meaning the serverN _and_ the dated folder are[ added to a TreeSet](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/8e4002bf1f8ebc3bfebe7df9a12a003ba0d1a9fe/bundle/src/main/java/com/adobe/acs/commons/workflow/bulk/removal/impl/WorkflowInstanceRemoverImpl.java#L328) and the comparator used to compare folder names expects the NN_DATE_FOLDER_PATTERN, which it doesn't get with "serverN"

As a temporary workaround, removing any dated workflow instance folders under /etc/workflow/instances, leaving any serverN folders, and restarting should make it work.

**Comment by cpilsworth** [comment]
If the desired behaviour should be to add the `/etc/workflow/instances` and the child serverN folders as roots, but ignore serverN as a child then it might be necessary to reintroduce [this change](https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/d4bd3483ac741a30946e9d105bf6aa2afb1bc76a#diff-67307694f86fa5353d0239ec52ff2ce9L223) removed in a merge.
