### ISSUE TITLE
AemEnvironmentIndicatorFilter doesn't check if the response is committed already

### ISSUE THREAD

**Issue by wimsymons** [Adobe-Consulting-Services/acs-aem-commons#841]
Stack trace:
```
09.11.2016 14:31:35.601 *WARN* [qtp1199086766-42102] org.eclipse.jetty.servlet.ServletHandler /system/console/status-slingthreads
java.lang.IllegalStateException: STREAM
        at org.eclipse.jetty.server.Response.getWriter(Response.java:920)
        at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:103)
        at org.apache.sling.engine.impl.log.RequestLoggerResponse.getWriter(RequestLoggerResponse.java:124)
        at com.adobe.acs.commons.wcm.impl.AemEnvironmentIndicatorFilter.doFilter(AemEnvironmentIndicatorFilter.java:178)
```

The filter should check if the response is an instance of javax.servlet.ServletResponseWrapper and check if the response is already committed or not before getting the writer from the response.

**Comment by wimsymons** [comment]
This happens in ACS Commons 2.7.2

**Comment by davidjgonzalez** [comment]
@wimsymons What version of AEM are you running? im trying to reproduce on 6.1 and 6.2.

1) What is the point of the the Wrapper check?
2) Your exception is happens on the back-end of the filter chain; if that response is committed (.getWriter() fails) then its too late to write the captured response to the response at all. 
3) We can check `response.isCommitted()` in `accepts(..)` but that happens before the rest of the chain is invoked.

**Comment by wimsymons** [comment]
Full stacktrace:
```
09.11.2016 14:31:35.601 *WARN* [qtp1199086766-42102] org.eclipse.jetty.servlet.ServletHandler /system/console/status-slingthreads
java.lang.IllegalStateException: STREAM
        at org.eclipse.jetty.server.Response.getWriter(Response.java:920)
        at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:103)
        at org.apache.sling.engine.impl.log.RequestLoggerResponse.getWriter(RequestLoggerResponse.java:124)
        at com.adobe.acs.commons.wcm.impl.AemEnvironmentIndicatorFilter.doFilter(AemEnvironmentIndicatorFilter.java:178)
        at org.apache.felix.http.base.internal.handler.FilterHandler.doHandle(FilterHandler.java:108)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:80)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:46)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:31)
        at org.apache.sling.security.impl.ReferrerFilter.doFilter(ReferrerFilter.java:290)
        at org.apache.felix.http.base.internal.handler.FilterHandler.doHandle(FilterHandler.java:108)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:80)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:46)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:31)
        at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:89)
        at org.apache.felix.http.base.internal.handler.FilterHandler.doHandle(FilterHandler.java:108)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:80)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:46)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:31)
        at org.apache.sling.featureflags.impl.FeatureManager.doFilter(FeatureManager.java:115)
        at org.apache.felix.http.base.internal.handler.FilterHandler.doHandle(FilterHandler.java:108)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:80)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:46)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:31)
        at org.apache.sling.engine.impl.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:75)
        at org.apache.felix.http.base.internal.handler.FilterHandler.doHandle(FilterHandler.java:108)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:80)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:46)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:31)
        at org.apache.felix.http.base.internal.dispatch.FilterPipeline.dispatch(FilterPipeline.java:76)
        at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:49)
        at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:67)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

We're running AEM 6.1 SP1.
It happens when you enable the environment indicator on the author instance as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
          jcr:primaryType="sling:OsgiConfig"
          css-color="#dc0030"
          css-override=""
          inner-html=""
          browser-title-prefix="PROD"
/>
```

Could it happen because the SSLFilter puts in some extra headers in the response?
The idea is to avoid the filter to change the response is the response is already committed. Now you can't request /system/console/status-slingthreads, you'll get a HTTP 500.

**Comment by wimsymons** [comment]
Sorry, I didn't notice that HttpServletResponse also has an isCommitted function.
Than, yes, the fix is to return false in the accepts() function when response.isCommitted() is true.

**Comment by davidjgonzalez** [comment]
![image](https://cloud.githubusercontent.com/assets/1451868/20183136/5a167558-a732-11e6-8046-098bc173a033.png)

@wimsymons mm.. possible the SSLFilter is doing something. Will have to fig into this further. I swear i checked 6.1 and `/system/console/status-slingthreads` wasnt even a console... it was `/system/console/status-Threads` ?

I wonder if pushing the AEM Env Filter down filter chain would help?

**Comment by wimsymons** [comment]
The SSLFilter is switched on because we run our author after a load balancer which offloads the ssl part. So all incoming http requests have an extra HTTP header `X-Forwarded-Protocol: https`.

**Comment by davidjgonzalez** [comment]
It should work generally w other filters; will need to poke around and see exactly what that ssl filter does

I was saying more what if the order was flipped; ssl first the aem env

**Comment by davidjgonzalez** [comment]
Er flip that, aem env first (can't edit comment on phone??)
