### ISSUE TITLE
Ensure Service User missing permissions

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#979]
com.adobe.acs.commons.users.impl.EnsureServiceUser-i18n-service.xml
 
```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0"
    xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="sling:OsgiConfig"
    principalName="i18n-service"
    type="add"
    ensure-immediately="{Boolean}true"
    aces="[type=allow;permissions=jcr:read;path=/apps/i18n]"/>
 ```
Error message without the action at #3:
 
```
21.04.2017 14:31:52.529 *WARN* [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.adobe.acs.commons.users.impl.EnsureServiceUser.7609b6ca-d48a-4ec2-a34e-c54e1d4a27ee)] com.adobe.acs.commons.users.impl.ServiceUser Malformed ACE config [ [type=allow;permissions=jcr:read;path=/apps/i18n, i18n-service] ] for Service User [ {} ]
com.adobe.acs.commons.users.impl.EnsureServiceUserException: Ensure Service User requires at least 1 privilege to apply.
                at com.adobe.acs.commons.users.impl.Ace.validate(Ace.java:98)
                at com.adobe.acs.commons.users.impl.Ace.<init>(Ace.java:89)
                at com.adobe.acs.commons.users.impl.ServiceUser.<init>(ServiceUser.java:42)
                at com.adobe.acs.commons.users.impl.EnsureServiceUser.activate(EnsureServiceUser.java:436)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                …
21.04.2017 14:31:52.536 *ERROR* [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.adobe.acs.commons.users.impl.EnsureServiceUser.7609b6ca-d48a-4ec2-a34e-c54e1d4a27ee)] com.adobe.acs.commons.users.impl.EnsureServiceUser Unable to ensure Service User [ true ]
com.adobe.acs.commons.users.impl.EnsureServiceUserException: Failed to ensure [ ADD ] of Service User [ i18n-service ]
                at com.adobe.acs.commons.users.impl.EnsureServiceUser.ensure(EnsureServiceUser.java:141)
                at com.adobe.acs.commons.users.impl.EnsureServiceUser.activate(EnsureServiceUser.java:440)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                …
Caused by: javax.jcr.AccessDeniedException: Missing permission to create intermediate authorizable folders.
                at org.apache.jackrabbit.oak.security.user.UserProvider.createFolderNodes(UserProvider.java:309)
                …
                at org.apache.jackrabbit.oak.jcr.delegate.UserManagerDelegator.createSystemUser(UserManagerDelegator.java:185)
                at com.adobe.acs.commons.users.impl.EnsureServiceUser.ensureSystemUser(EnsureServiceUser.java:201)
                at com.adobe.acs.commons.users.impl.EnsureServiceUser.ensureExistance(EnsureServiceUser.java:158)
                at com.adobe.acs.commons.users.impl.EnsureServiceUser.ensure(EnsureServiceUser.java:125)
                ... 54 common frames omitted
```

**Comment by davidjgonzalez** [comment]
Closing as dupe of #978
